import type { Explainer } from "./types";

/**
 * The written guides behind each screen's "How to" button.
 *
 * Every **bold** phrase is a label the screen really shows, spelled the way
 * it spells it — tests/help-content.test.ts fails when one no longer exists
 * in the source, so a renamed button can't leave a guide describing the old
 * one. Plan: docs/how-to-videos-plan-2026-09-30.md (§2a lists the rest).
 */
export const EXPLAINERS: readonly Explainer[] = [
  // ── Studio ────────────────────────────────────────────────────────────
  {
    id: "tour",
    title: "A tour of StudioCue",
    summary: "The four places that do most of the work, and where everything else lives.",
    audience: "studio",
    stage: "getting-started",
    routes: ["/studio/help", "/studio/help/journey"],
    video: "tour",
    purpose:
      "StudioCue runs your studio from the first inquiry to the final gallery. Four places in the menu do most of the work.",
    steps: [
      "**Today** is your inbox: everything that needs a decision, most urgent first. Drafts StudioCue has written wait under **Prepared for you** — **Approve** them as they are, or **Review** them first.",
      "**Inquiries** holds everyone who hasn't booked yet, by stage — **New**, **Talking**, **Consult**, **Proposal**, **Signing** — and shows whose move it is.",
      "**Jobs** holds every booked wedding. Open one to see its whole story and **Your next move**.",
      "**Cue** is your assistant. Ask it to draft an email, prepare a proposal or tell you what's outstanding — it prepares, you approve.",
      "**Calendar**, **Messages**, **Clients** and **Insights** sit under **More** on a phone. Your packages and templates live in **Library**.",
    ],
    next: "Every screen has a **How to** button at the top. It opens the guide for whatever you're looking at.",
    goodToKnow: [
      "Drafts wait for your approval. The exceptions are the routine emails you set to send automatically, and the ones your workflows send on schedule.",
      "Just starting? **Continue setup** on Today walks you through the essentials.",
    ],
    terms: ["today", "job", "inquiry", "cue", "prepared"],
  },
  {
    id: "today",
    title: "Work from Today",
    summary: "Start each day here: decide what's waiting, approve what's drafted, and leave the rest.",
    audience: "studio",
    stage: "every-day",
    routes: ["/studio"],
    alsoOn: ["/studio/notifications", "/studio/tasks", "/studio/tasks/**"],
    video: "today",
    purpose:
      "Today shows everything waiting on you, most urgent first, and keeps track of everything else. If nothing is waiting, nothing is wrong.",
    steps: [
      "Read the headline. It's the single most urgent thing; **You're all clear.** means nothing needs you.",
      "Work through **Prepared for you** — replies, reminders and bills StudioCue has drafted. **Approve** sends one as written; **Review** opens it so you can edit it first.",
      "For a new inquiry, read the **Reply ready** draft and tap **Send reply**, or **Edit** it first. If it isn't really an inquiry, tap **Not an inquiry**.",
      "Then clear what's under **Only you can do this** — the decisions StudioCue can't make for you. Each one opens where you finish it.",
      "When a couple goes quiet, you'll be asked to **Close — went quiet** or **Keep it open**.",
    ],
    next: "Anything waiting on someone else sits under **In motion** and comes back to Today by itself when it needs you again.",
    goodToKnow: [
      "**Handled for you** lists what StudioCue did without you, so you can always check.",
      "A reply only includes a booking link once your consultation hours are set.",
    ],
    terms: ["today", "prepared", "inquiry"],
  },
  {
    id: "inquiry",
    title: "Answer a new inquiry",
    summary: "Reply fast, follow up without remembering to, and close the ones that don't book.",
    audience: "studio",
    stage: "inquiry-to-booking",
    routes: ["/studio/leads", "/studio/leads/*"],
    alsoOn: ["/studio"],
    video: "inquiry",
    purpose:
      "Inquiries holds everyone who's asked about a date but hasn't booked. A confirmed inquiry with a date becomes a job straight away, so nothing slips.",
    steps: [
      "Open **Inquiries**. **Open** shows everyone still in play; the other tabs split them by stage, from **New** to **Signing**. **Your move** marks the ones waiting on you.",
      "Answer from **Today**: StudioCue drafts a reply to each new inquiry. Read it, then **Send reply**. It includes a link where the couple can add details and pick a consultation time.",
      "Unsure emails arrive as **Maybe an inquiry** — tap **Yes, an inquiry** or **Not an inquiry**.",
      "No answer? A follow-up is drafted on day 3 and day 7, ready for **Send follow-up**.",
      "If it doesn't book, open the job, choose **Close inquiry** and pick why — **Went quiet**, **Booked someone else**, **Budget** and so on.",
    ],
    next: "Once they book a consultation the inquiry moves to **Consult**, and a proposal comes next. When they sign and pay the retainer, it leaves Inquiries for **Jobs**.",
    goodToKnow: [
      "**Preview inquiry form** shows the form couples fill in. Put its link on your website and every submission lands here.",
      "Inquiries by email, The Knot or WeddingWire can be forwarded in — **Copy address** and forward to it from your inbox.",
      "A closed inquiry reopens by itself if the couple writes again.",
    ],
    terms: ["inquiry", "inquiry-link", "forwarding-address", "consultation", "lost"],
  },
  {
    id: "proposal",
    title: "Build and send a proposal",
    summary: "Package, extras, price and payment dates — drafted for you, approved by you, sent in one tap.",
    audience: "studio",
    stage: "inquiry-to-booking",
    routes: ["/studio/proposals", "/studio/proposals/**"],
    alsoOn: ["/studio/booking"],
    video: "proposal",
    purpose:
      "A proposal is what a couple sees before they book: their packages, any extras, the price and the payment dates. You build it, approve it, then send it.",
    steps: [
      "On the job's **Booking** tab choose **Prepare the proposal**, or start from the proposals list with **New proposal**.",
      "Under **Choose the client and event**, check the couple and the packages they're booking.",
      "Under **Frame the offer**, tap **Draft from what they told you** for an introduction written from their inquiry, then make it yours.",
      "Set **Proposal expires**, **Retainer due** and **Final balance due**, then **Create draft**. Nothing is sent yet.",
      "Add an album or other extra with **Add from your library**, or **Write one for this couple**.",
      "Check it over, **Approve this proposal**, tick **Ready to share with the client** and **Send proposal**.",
    ],
    next: "The couple gets a branded email with the proposal and a link to their portal, where they **Accept proposal** or **Request changes**. Once they accept, signing the agreement is their next step.",
    goodToKnow: [
      "Team members who aren't an owner or admin see **Send for approval** instead.",
      "Need to change it after sending? **Correct and re-issue** sends a new version.",
      "Accepted by phone or email? **Record the acceptance**.",
    ],
    terms: ["proposal", "package", "add-on", "retainer", "final-balance"],
  },
  {
    id: "contract-retainer",
    title: "Get it signed and the retainer paid",
    summary: "Send the agreement, raise the retainer, and confirm the booking.",
    audience: "studio",
    stage: "inquiry-to-booking",
    routes: ["/studio/booking", "/studio/contracts"],
    alsoOn: ["/studio/invoices", "/studio/projects/*"],
    video: "contract-retainer",
    purpose:
      "A job is booked when two things are in: the signed agreement and the paid retainer. Both happen on the job's **Booking** tab.",
    steps: [
      "Open the job's **Booking** tab. The strip at the top — **Contract**, **Retainer**, **Booking** — shows what's next.",
      "Send the agreement: **Prepare the contract**, type your name to sign for the studio, then **Sign & send**. With Dropbox Sign or Docusign connected, it's **Approve sequence & send**.",
      "Once it's signed, **Create retainer invoice**. The couple pays it online.",
      "Signed or paid outside StudioCue? **Record the signature** or **Record the payment**. Booking without a retainer? **Confirm the booking without a retainer**.",
      "Under **Confirm booking**, tap **Check and confirm**. When **Automatic confirmation is active**, it confirms by itself.",
    ],
    next: "The job turns Booked, moves from Inquiries to **Jobs**, and planning begins: questionnaire, crew and run of show.",
    goodToKnow: [
      "Recording a payment doesn't book the job by itself — confirm the booking to finish.",
      "With StudioCue signing, the couple is reminded to sign after 3 and 7 days.",
      "The retainer invoice goes through QuickBooks, so connect it first.",
    ],
    terms: ["agreement", "retainer", "booking-gate"],
  },
  {
    id: "job-page",
    title: "Follow one wedding from start to finish",
    summary: "Where a job is, the one thing to do next, and everything that's happened.",
    audience: "studio",
    stage: "every-day",
    routes: ["/studio/projects", "/studio/projects/*", "/studio/projects/new", "/studio/planning"],
    video: "job-page",
    purpose:
      "Every client has one job: their whole story in one place, from inquiry to closeout. Open it from **Jobs** or from any card on Today.",
    steps: [
      "Open **Jobs** and pick a wedding. **Active** and **Archived** split them, and the chips filter by type.",
      "The track along the top shows where it is: **Inquiry**, **Booking**, **Preparation**, **The day**, **Delivery**.",
      "Start with **Your next move** — the one thing to do now. **Nothing for you right now** means it's waiting on someone else.",
      "Drafts for this job wait under **Prepared for you**, ready to approve.",
      "The tabs — **Overview**, **Booking**, **Plan**, **Delivery** — hold each stage's detail.",
      "Keep the record in **Job history**: **Log a call**, **Ask Cue** about the job, or **Add a task**.",
    ],
    next: "As the couple signs, pays and fills things in, the job moves along the track by itself.",
    goodToKnow: [
      "**Edit job** changes the date, venue or type; **Add a client** adds a second contact.",
      "A new client? **New job** starts a job from their message.",
      "Weddings booked before StudioCue? **Import bookings** brings them in without emailing anyone.",
    ],
    terms: ["job", "readiness"],
  },

  {
    id: "setup",
    title: "Set up your studio",
    summary: "Seven questions that get StudioCue ready for your first real inquiry.",
    audience: "studio",
    stage: "getting-started",
    routes: ["/studio/setup", "/studio/settings", "/studio/settings/*"],
    video: "setup",
    purpose:
      "Setup asks seven questions: what you shoot, how inquiries reach you, when couples can book a call, what you charge, how clients sign, what you ask couples, and who sends your insurance certificates. Most are answered right on the page.",
    steps: [
      "On Today, tap **Continue setup**. Each question says why it matters.",
      "**How do inquiries reach you?** Pick a route, from **On your website** to **Inbox rules**.",
      "**When can clients book a call?** Tap **Use Mon–Fri, 9–5** or **Choose my own hours**, and **Connect Google Calendar** so busy times are never offered.",
      "**What do you charge?** **Paste or upload your prices**, or **Add one by hand**.",
      "**How do your clients sign?** Set up your agreement in StudioCue, or tap **I send my own agreement**.",
      "Finish with your questionnaire and **Who sends your certificates of insurance?**",
    ],
    next: "Skip anything you like: StudioCue brings it back on Today when a job actually needs it. Change any answer later in **Studio settings**.",
    goodToKnow: [
      "Your studio's name, logo and email colours are in **Studio settings**, under **Studio details** and **Email branding**.",
    ],
    terms: ["forwarding-address", "consultation", "agreement"],
  },
  {
    id: "import-bookings",
    title: "Bring in the weddings you've already booked",
    summary: "Import existing bookings one at a time or from a spreadsheet, without emailing anyone.",
    audience: "studio",
    stage: "getting-started",
    routes: ["/studio/projects/import"],
    purpose:
      "Bring in the weddings you booked before StudioCue, one at a time or from a spreadsheet, without anything going to the couples.",
    steps: [
      "Open **Jobs** and choose **Import bookings**.",
      "For one wedding, fill in **The couple**, **The event**, **The contract** and **Paid so far**, then **Check booking** and **Import booking**.",
      "For many, go to **A spreadsheet of bookings**. **Download a template** if you need one, **Choose a CSV file**, check the columns, then import.",
      "When you're ready to work with a couple, open their job and tap **Bring this couple into StudioCue**.",
    ],
    next: "Imported jobs come in quiet: no emails, invoices or reminders reach the couple until you bring them in. Inviting them to their portal is a separate tick.",
    goodToKnow: [
      "**Fill from QuickBooks** takes what's been paid from QuickBooks, matched by the client's email. Nothing in QuickBooks changes.",
      "Only owners and admins can import.",
    ],
    terms: ["quiet-import", "job"],
  },
  {
    id: "packages",
    title: "Add your packages, add-ons and price list",
    summary: "Set up what you sell once, and every proposal draws on it.",
    audience: "studio",
    stage: "getting-started",
    routes: ["/studio/packages", "/studio/packages/*", "/studio/library", "/studio/library/*", "/studio/import"],
    purpose: "Packages are what you sell; add-ons are the extras. Set them up once and every proposal draws on them.",
    steps: [
      "Open **Library**, choose **Packages**, then **Create package**.",
      "Set the **Base price (USD)**, the **Retainer type** — a percent, a fixed amount or per crew member — and who you send under **Photographers** and **Videographers**.",
      "Under **What this package delivers**, list the gallery, film or album and when each is due.",
      "Add extras under **Add-ons** with **New add-on**, and tick the ones a package should suggest.",
      "Already have a price list? **Open AI import studio** and **Upload files**. Nothing goes live until you activate it.",
    ],
    next: "Proposals are built from your packages. Changing a package never changes the price on a proposal or booking that already has it.",
    goodToKnow: [
      "**Show this package to clients** lets couples ask for it from their portal. New and imported packages start with it off.",
      "Retire a package by turning off **Available to book**; past bookings keep it.",
    ],
    terms: ["package", "add-on", "coverage", "retainer"],
  },
  {
    id: "agreement",
    title: "Upload your contract",
    summary: "Turn your contract into a template StudioCue fills in for every couple.",
    audience: "studio",
    stage: "getting-started",
    routes: ["/studio/contracts/agreement"],
    purpose:
      "Your agreement is the contract template StudioCue writes each couple's contract from, filling in names, dates, coverage and prices from the job.",
    steps: [
      "From setup, choose **Set up your agreement**.",
      "**Upload your contract**. StudioCue reads it and turns names, dates and prices into fields, or you can write it in the editor.",
      "Insert details with the field buttons, like **Client names**, **Total price** or **Payment schedule (table)**. Use **+ Your own field** for anything else.",
      "Check the **Preview with sample details**, then **Save your agreement**.",
      "Choose what happens **When a proposal is accepted**: StudioCue prepares the contract for you to send, or signs and sends it for you.",
    ],
    next: "Each accepted proposal writes a contract from the latest version. Contracts already sent keep the version they were sent with.",
    goodToKnow: [
      "A contract with one of your own fields still blank never sends by itself.",
      "Seeing **Not switched on yet**? Writing contracts in StudioCue is turned on per studio; ask StudioCue support.",
      "Prefer your own paperwork? Record the signature on the job's **Booking** tab instead.",
    ],
    terms: ["agreement", "proposal"],
  },
  {
    id: "inquiry-capture",
    title: "Put your inquiry form on your website",
    summary: "Get every inquiry into StudioCue automatically, from your website, your own form or your inbox.",
    audience: "studio",
    stage: "getting-started",
    routes: ["/studio/settings/inquiry-capture"],
    alsoOn: ["/studio/leads"],
    video: "inquiry-capture",
    purpose:
      "Get every inquiry into StudioCue automatically — from your website, your own form or your inbox — each with its date checked and a reply drafted.",
    steps: [
      "Open **Studio settings** and choose **Inquiry capture**.",
      "Easiest: **Put your inquiry form on your website**. Pick your website builder, copy the code and paste it in.",
      "Keeping your own form? Choose **Keep your own website form** and add **Your StudioCue address** as a second recipient.",
      "For The Knot, WeddingWire or email, use **Forward by hand**, or **Forward automatically from your inbox** with a Gmail filter or Outlook rule.",
      "Tap **Test** and send yourself a test inquiry. If a field lands in the wrong place, fix it and tap **Looks right**.",
    ],
    next: "Every inquiry lands in **Inquiries** and on Today with a reply drafted. The couple hears nothing until you send it.",
    goodToKnow: ["Save **Your StudioCue address** as a contact so forwarding takes two taps."],
    terms: ["forwarding-address", "inquiry", "inquiry-link"],
  },
  {
    id: "integrations",
    title: "Connect your tools",
    summary: "Google Calendar, Zoom, Dropbox and QuickBooks — what each does in StudioCue.",
    audience: "studio",
    stage: "getting-started",
    routes: ["/studio/integrations"],
    purpose:
      "Connect the tools StudioCue works through: Google Calendar for availability, Zoom for calls, Dropbox for files and QuickBooks Online for invoices and payments.",
    steps: [
      "Open **Integrations**. Each tile says what StudioCue uses that tool for.",
      "Tap **Connect** and sign in to the tool.",
      "Use **Test** to check a connection, and **Manage** to see its activity or disconnect it.",
      "Read the summary line: **Not covered yet** lists jobs that nothing you've connected can do.",
      "For autopay, open the **Autopay** tab and follow its three steps.",
    ],
    next: "StudioCue starts using a tool as soon as it's connected: busy calendar times stop being offered, and invoices sync with QuickBooks.",
    goodToKnow: [
      "Sign-in details are encrypted and never shown in the browser.",
      "Autopay needs QuickBooks Payments, which Intuit approves for your business.",
    ],
    terms: ["autopay"],
  },
  {
    id: "cue",
    title: "Ask Cue, then approve",
    summary: "Ask your assistant anything, or ask it to do something — it prepares, you approve.",
    audience: "studio",
    stage: "every-day",
    routes: ["/studio/copilot", "/studio/ai-queue"],
    purpose:
      "Cue is your assistant. Ask it anything about your studio, or ask it to do something, and it prepares the work for you to approve.",
    steps: [
      "Open **Cue** and type into **Message Cue**, or pick a suggestion.",
      "Type a slash for a ready-made question, like /attention for today's priorities or /unpaid for balances owed.",
      "When Cue prepares something, it shows as a card. Nothing happens until you tap its button.",
      "Drafted emails wait under **Prepared for you** on Today and in AI review: **Approve & send**, **Edit first**, **Reject** or **Dismiss**.",
      "**New conversation** starts afresh; earlier ones stay under **Pick up where you left off**.",
    ],
    next: "Cue answers from your studio's records and shows where each fact came from.",
    goodToKnow: [
      "**Reject** tells StudioCue the draft was wrong so it learns; **Dismiss** just means not now.",
      "Cue can never take a payment, sign anything or mark a job ready on its own.",
    ],
    terms: ["cue", "prepared"],
  },
  {
    id: "messages",
    title: "Message a couple",
    summary: "Every conversation with your couples, with replies drafted when they write in.",
    audience: "studio",
    stage: "every-day",
    routes: ["/studio/messages"],
    purpose: "Messages holds every conversation with your couples, with a reply drafted for you when they write in.",
    steps: [
      "Open **Messages**. Conversations waiting on you are counted at the top.",
      "To start one, tap **New message**, choose the **Project** and **Client**, write it and tap **Send message**.",
      "When a couple writes in, a reply is often ready: tap **Use this reply**, edit it, then **Send reply**. Or tap **Draft a reply**.",
      "Each message shows whether it was **Delivered**, **Opened** or **Did not arrive**.",
    ],
    next: "Couples read and answer in their portal and by email; their replies land back here.",
    goodToKnow: [
      "A coordinator's message about money, the contract or insurance waits for an owner under **Waiting for your approval**.",
      "Files a couple attaches show inside their message.",
    ],
  },
  {
    id: "consultation",
    title: "Book a consultation",
    summary: "Set when couples can book a call, and see every call and event on one calendar.",
    audience: "studio",
    stage: "inquiry-to-booking",
    routes: ["/studio/calendar", "/studio/settings/consultation-availability"],
    purpose: "Set when couples can book a call with you, and see every consultation and event on one calendar.",
    steps: [
      "Open **Calendar** and tap **Manage availability**.",
      "Choose **Closed by default** (only the hours you add) or **Open by default** (everything but the times you mark unavailable), then set your hours.",
      "Under **How you meet**, pick **Video call**, **In person** or **Phone call**, and set the **Consultation length (minutes)**.",
      "Tap **Save availability**. Your first reply to each inquiry now carries a link where the couple picks a time.",
      "To book one yourself, tap an open slot, **Book**, then **Confirm booking**.",
    ],
    next: "Booked calls show on the calendar and on the job. **Move to…** or **Cancel** updates the invitation and any Zoom meeting.",
    goodToKnow: [
      "**Connect Google Calendar** and your busy times are never offered.",
      "A video call sends a Zoom link with the confirmation.",
    ],
    terms: ["consultation", "inquiry-link"],
  },
  {
    id: "booking-change",
    title: "Change a booking after it's signed",
    summary: "A new date or a different package, signed by the couple as an amendment.",
    audience: "studio",
    stage: "inquiry-to-booking",
    routes: [],
    alsoOn: ["/studio", "/studio/projects/*"],
    purpose:
      "Once a couple has signed, a new date or a change of package is a booking change: they sign an amended agreement, and the job keeps its place.",
    steps: [
      "Open the job and choose **Change the booking**. If the couple asked from their portal, Today shows **Write up the change**.",
      "Set the new **Wedding date**, or add or remove **Packages**. Tick any **Calls with the couple** that should move too.",
      "Add **A note for the couple (optional)** and tap **Write up the change**. Nothing changes yet.",
      "Check the new total, read the amended agreement, sign with your name and tap **Sign & send to the couple**.",
      "Signed on paper? Tap **They signed it another way**, then **Record their signature**.",
    ],
    next: "The couple signs in their portal. Until then their current agreement stands; when they sign, the job takes the change and what they've paid carries over.",
    goodToKnow: [
      "Before the agreement goes out, change packages on the proposal instead, under **What they're booking**.",
      "If money is owed and the wedding is close, a new final bill is raised.",
    ],
    terms: ["booking-change", "agreement"],
  },
  {
    id: "final-balance",
    title: "Collect the final balance",
    summary: "How the last bill goes out, what to do when it can't, and how autopay takes it for you.",
    audience: "studio",
    stage: "planning",
    routes: ["/studio/invoices"],
    alsoOn: ["/studio", "/studio/integrations"],
    purpose:
      "The final balance is what's left after the retainer. StudioCue bills it 28 days before the wedding when it can, and asks you on Today when it can't.",
    steps: [
      "Most final bills go out by themselves, 28 days before the wedding, through QuickBooks or Stripe.",
      "When one can't — booked late, date moved, retainer recorded by hand — Today shows it. Tap **Send the final bill**.",
      "Paid by transfer, cheque or cash? Tap **Paid another way** and record it.",
      "See what's owed on **Invoices**. **Final invoice review** shows how each bill was worked out.",
      "Turn on autopay under **Integrations**, on the **Autopay** tab: couples save a card and the balance pays itself on its due date.",
    ],
    next: "The couple gets the invoice by email and pays online. It's due 14 days before the wedding.",
    goodToKnow: [
      "Autopay needs QuickBooks Payments.",
      "A declined autopay card gets the invoice link and one retry three days later.",
    ],
    terms: ["final-balance", "retainer", "autopay"],
  },
  {
    id: "questionnaire",
    title: "Send the questionnaire",
    summary: "Collect names, timings and key moments from the couple, with reminders sent for you.",
    audience: "studio",
    stage: "planning",
    routes: ["/studio/questionnaires", "/studio/questionnaires/*"],
    alsoOn: ["/studio/planning"],
    purpose:
      "Questionnaires collect what you need from the couple — names, timings, the key moments — without long email threads.",
    steps: [
      "Open the job's **Plan** tab and choose **Client details**, or open **Questionnaires**.",
      "If StudioCue has a form for this kind of job, tap **Send the form**. Otherwise pick a template and **Assign questionnaire**.",
      "To start from ours, use **Make a copy** under Ready-to-use wedding forms. To build your own, choose **Build template**, add questions with **Add a question here** (and sections with **Add a section**), then **Save template**. Only **Active** templates can be sent.",
      "When the couple sends it back, open it to read their answers and **What StudioCue noticed**.",
    ],
    next: "The couple fills it in from their portal, with reminders before it's due (7, 3 and 1 days unless you change them on the form). The due date is worked out from the wedding date.",
    goodToKnow: [
      "Editing a template saves a new version; forms already sent keep their questions.",
      "Questions marked **Crew see it** show up in your photographers' brief.",
      "Each question can show only after an earlier answer, or suggest a time from an earlier time — open **When it shows** under it. Moving a question above the one it depends on clears that rule, and the editor says so.",
    ],
  },
  {
    id: "run-of-show",
    title: "Build the run of show and share it",
    summary: "Draft the day's timeline, publish it to your crew and couple, and share it with vendors.",
    audience: "studio",
    stage: "planning",
    routes: ["/studio/schedules", "/studio/schedules/*", "/studio/vendors"],
    alsoOn: ["/studio/planning"],
    purpose:
      "The run of show is the wedding day's timeline. You draft it, the couple approves it, and crew and vendors work from it.",
    steps: [
      "From the job's **Plan** tab choose **Open the run of show**, or tap **Generate schedule** on Schedules.",
      "Fill in what you know — **Coverage starts**, **Ceremony time**, the locations — and tap **Generate draft**. Anything left blank is guessed and labelled.",
      "Adjust the items under **The day**. Check **What we assumed**, and ask the couple about anything in **What we still need**.",
      "Tap **Publish reviewed schedule**.",
      "For vendors, open **Share run of show**, tap **Create share link** and send it to them.",
    ],
    next: "Accepted crew get it on their day sheet and are asked to confirm it; the couple is asked to approve the parts meant for them. Each publish is a new version.",
    goodToKnow: [
      "Your **Timing rules** — how long portraits take, the buffers — shape every draft once you approve them.",
      "Vendors see only their own parts and shared items, never your notes.",
    ],
    terms: ["run-of-show"],
  },
  {
    id: "crew-offer",
    title: "Book your second shooter",
    summary: "StudioCue ranks who to ask and offers the job one person at a time until someone accepts.",
    audience: "studio",
    stage: "planning",
    routes: ["/studio/crew", "/studio/crew/*"],
    alsoOn: ["/studio/planning", "/studio/projects/*"],
    video: "crew-offer",
    purpose:
      "Book second shooters and assistants for a job. StudioCue ranks who to ask and offers the job to one person at a time until someone accepts.",
    steps: [
      "Open the job's **Plan** tab and choose **Crew for this job**, or tap **Staff this job** on the job page.",
      "If offers were **Prepared when this job was booked**, check them and tap **Send these offers**.",
      "Otherwise choose **Rank my options**, set the roles, times, rate and **Response window**, then **Approve crew plan and start**.",
      "Know exactly who you want? Choose **I know who I want** and **Send offer**.",
      "Nobody accepted? **Offer to someone else** starts a new round without asking the same people.",
    ],
    next: "Each person gets an email and answers from their phone. If they decline or the window runs out, the next name is asked.",
    goodToKnow: [
      "Before the day, crew send their W-9 and any insurance; you approve or waive each item.",
      "After the job, approve their hours and set **Payment status**. StudioCue doesn't pay anyone for you.",
    ],
    terms: ["crew-offer"],
  },
  {
    id: "coi",
    // Not "a venue's insurance certificate": it is the studio's own
    // certificate, naming the venue.
    title: "Send a venue your insurance certificate",
    summary: "Your agent issues it, StudioCue asks and chases, and the venue gets it once you approve.",
    audience: "studio",
    stage: "planning",
    routes: ["/studio/insurance"],
    alsoOn: ["/studio/planning"],
    purpose:
      "Many venues want a certificate of insurance — proof of your liability cover, naming them — before the day. StudioCue asks your insurance agent for it, chases it, checks it, and sends it on once you've approved it.",
    steps: [
      "Once, in **Studio settings** → **Insurance**, save your agent's email and choose how far StudioCue goes: **Prepare it**, **Send it** or **Off**.",
      "Say the venue needs one: the couple answers on your inquiry form, or tap **Yes, it does** under **Venue & insurance** on the job's **Plan** tab.",
      "60 days before the event, StudioCue asks your agent — or, on **Prepare it**, puts **Send the COI request to your agent** on Today for you.",
      "Your agent replies with the PDF and it comes straight back to the job. StudioCue checks it against the venue's requirements and flags any differences.",
      "Read it, then tap **Approve & send to venue** — or **Ask agent to correct**.",
    ],
    next: "StudioCue follows up with your agent every 3 days, up to 4 times, then tells you on Today. Once the venue has the certificate, the readiness checkpoint ticks.",
    goodToKnow: [
      "StudioCue flags possible problems, but you always decide whether a certificate is right.",
      "The venue's wording is remembered: the next wedding there needs no typing.",
    ],
    terms: ["coi"],
  },
  {
    id: "readiness",
    title: "Know the wedding is ready",
    summary: "The checklist every booked wedding clears before the day, and the event-day brief.",
    audience: "studio",
    stage: "planning",
    routes: ["/studio/readiness", "/studio/event-day"],
    purpose:
      "Readiness is the checklist a booked wedding must clear before the day. Most items tick themselves as records arrive; the judgement calls are yours.",
    steps: [
      "Open **Event readiness** to see each job's **Score**, what's **Blocking** and what's **Overdue**.",
      "Open a job to see its **Readiness checkpoints**. Items settle themselves when the record arrives: a signature, a payment, an accepted offer.",
      "For a judgement call, tap **Mark done** and say how you know. To skip one, tap **Waive** and say why.",
      "On the day, open **Event day** for the venue, the run of show and who's working, and **Ask the event brief** anything.",
    ],
    next: "Your reasons are saved to the audit log under your name, and readiness shows them as your call rather than something StudioCue saw.",
    goodToKnow: ["A job counts as ready only when every required checkpoint is settled."],
    terms: ["readiness", "checkpoint"],
  },
  {
    id: "delivery",
    title: "Deliver the gallery and close out",
    summary: "Send the finished photos or film, then close the job once everything reconciles.",
    audience: "studio",
    stage: "after-the-wedding",
    routes: ["/studio/delivery", "/studio/post-production", "/studio/post-production/*"],
    video: "delivery",
    purpose: "Send the finished photos or film to the couple, then close the job once everything reconciles.",
    steps: [
      "Open the job's **Delivery** tab. Tick **Cards backed up** first; nothing is released before it.",
      "Under **This release**, add each item: **What it is**, the **Link**, any **Access code**, and **Downloads until**.",
      "Or forward your gallery host's “ready” email to the job, then **Read the link and code**.",
      "Add your **Review link**, then **Release to the couple**.",
      "When everything is in, use **Close and archive** under **Closing the job**. Anything that happened elsewhere can be vouched for with **Mark as done**.",
    ],
    next: "The couple gets one email with a button for each item and their codes, and everything lands in their portal. Review requests follow 3 and 10 days later.",
    goodToKnow: [
      "Films have no download deadline; WeTransfer links last 7 days.",
      "Only owners and admins can close a job.",
    ],
    terms: ["closeout"],
  },
  {
    id: "reviews",
    title: "Ask for a review",
    summary: "Two asks after delivery, which stop as soon as the couple has left one.",
    audience: "studio",
    stage: "after-the-wedding",
    routes: ["/studio/reviews"],
    purpose:
      "Review requests ask each couple for a review after their final delivery, then stop as soon as they've left one.",
    steps: [
      "Add your review link when you release the final delivery; it's needed then.",
      "StudioCue asks twice: a note in the couple's portal 3 days after delivery, then an email at 10 days.",
      "Open **Review requests** to see what's scheduled and what's gone out.",
      "When the couple taps **I've left my review**, or you confirm it, the remaining asks are cancelled.",
    ],
    next: "Nothing is sent for a job that's been archived, cancelled or kept quiet since delivery.",
    goodToKnow: ["Want to ask in your own words? Ask Cue to **Draft a review request**."],
  },
  {
    id: "insights",
    title: "Read your Insights",
    summary: "Bookings, money, where inquiries come from, and what StudioCue handled for you.",
    audience: "studio",
    stage: "admin",
    routes: ["/studio/reports", "/studio/reports/**"],
    purpose:
      "Insights shows how the studio is doing: bookings, money, where inquiries come from, and what StudioCue handled for you.",
    steps: [
      "Open **Insights**, set the **Report range**, and narrow by **Project type** if you like.",
      "Read the top line: **Booked jobs**, **Average readiness**, **Invoiced** and **Outstanding**.",
      "**Where inquiries come from** shows which sources turn into bookings.",
      "**Where inquiries stop becoming bookings** shows the step where couples drop off.",
      "**What StudioCue handled for you** counts the approvals, sends and time saved.",
    ],
    next: "Use **Export CSV** or **Print** to share it. QuickBooks stays the record for your books.",
    goodToKnow: ["The range filters jobs by their event date, and inquiries by the date they arrived."],
  },
  {
    id: "people",
    title: "Clients, crew, team and vendors",
    summary: "Where each kind of person lives in StudioCue, and how to add them.",
    audience: "studio",
    stage: "admin",
    routes: ["/studio/clients", "/studio/clients/*", "/studio/crew/new"],
    alsoOn: ["/studio/vendors", "/studio/crew", "/studio/team"],
    purpose: "Clients, crew, team and vendors each have their own list, one tap apart.",
    steps: [
      "Open **Clients**. Along the top are **Clients**, **Crew**, **Team** and **Vendors**.",
      "**Add client** creates a contact. Their email becomes their portal login.",
      "**Crew** are freelancers you offer jobs to. **Add crew member** emails them an invite to set their availability and send their papers.",
      "**Team** are people who sign in to help run your studio.",
      "**Vendors & venues** are saved against a job: **Add vendor**, choosing the job they're working.",
    ],
    next: "Clients usually arrive by themselves from inquiries, so you'll rarely add one by hand.",
    goodToKnow: ["Adding a crew member doesn't put them on a job; offers come from each job's crew plan."],
  },
  {
    id: "team",
    title: "Invite your team",
    summary: "Add the people who help run your studio, and choose what each can do.",
    audience: "studio",
    stage: "admin",
    routes: ["/studio/team"],
    purpose: "Invite the people who help run your studio, and choose what each of them can do.",
    steps: [
      "Open **Clients**, then **Team** along the top.",
      "Under **Add someone to your studio**, enter a **Name** and **Email** and pick a **Role**.",
      "Tap **Send invitation**. They get an email, and you can also copy the **Invitation link**.",
      "Change a role any time from the **Role** menu on their row. **Suspend** pauses their access; **Remove** ends it.",
    ],
    next: "They join once they accept, and see only what their role allows.",
    goodToKnow: [
      "Only the studio owner can manage the team.",
      "Crew are freelancers you offer jobs to: add them under **Crew**, not here.",
    ],
    terms: ["studio-roles"],
  },
  {
    id: "automations",
    title: "Workflows and automatic emails",
    summary: "The checkpoints and emails every booked job gets, and which emails wait for you.",
    audience: "studio",
    stage: "admin",
    routes: [
      "/studio/workflows",
      "/studio/workflows/**",
      "/studio/automations",
      "/studio/settings/automatic-drafts",
      "/studio/settings/email-templates",
    ],
    purpose:
      "Workflows set the checkpoints and automatic emails every booked job gets. Automatic drafts and email templates decide how routine emails are written and sent.",
    steps: [
      "Open **Library**, choose **Workflow templates**, then **Create workflow**.",
      "Name it, pick the **Event type**, and choose the **Starting checkpoints** — the milestones every job must reach, dated back from the event.",
      "Review **Starting automations**. Email automations go to the client on schedule without a draft to approve, so untick any you'd rather send yourself.",
      "Set **Availability** to publish it for new jobs, then **Create workflow**.",
      "In **Studio settings**, **Automatic drafts** sets whether each routine email waits for you (**Review each time**) or sends itself (**Send automatically**).",
    ],
    next: "New jobs of that type get the workflow when they're booked. **Automation runs** shows each time an automation ran and whether it worked.",
    goodToKnow: [
      "Publishing under the same name replaces the old version; jobs already running keep theirs.",
      "For email templates, **Save new version** only saves a draft — **Activate** makes it the one that's used.",
    ],
    terms: ["workflow", "checkpoint", "readiness"],
  },
  {
    id: "subscription",
    title: "Your plan and billing",
    summary: "What you're on, what you're using, and where to change your card.",
    audience: "studio",
    stage: "admin",
    routes: ["/studio/subscription"],
    purpose: "See your plan and what you're using against it, change plan, and manage how you pay.",
    steps: [
      "Open **Studio settings** and choose **Plan & billing**.",
      "Check **Internal users**, **AI actions · current month** and **Active subcontractors** against your plan.",
      "Compare plans under **Plans** and switch when you need more room.",
      "Update your card or get your invoices with **Open customer portal**.",
    ],
    next: "Changes take effect straight away. Payment details stay with Stripe; StudioCue never sees your card.",
    goodToKnow: ["Each AI task, like drafting a message or reading an import, counts as one AI action. There's also a daily cap."],
  },

  // ── Couple ────────────────────────────────────────────────────────────
  {
    id: "couple-tour",
    title: "Your wedding portal",
    summary: "Where everything between booking and your photos happens.",
    audience: "couple",
    stage: "getting-started",
    routes: ["/client", "/client/plan", "/client/project"],
    video: "couple-tour",
    purpose:
      "This is your wedding portal. Everything between booking and your photos happens here, and your photographer sees what you do straight away.",
    steps: [
      "**Home** shows the countdown to your day and **Your next step** — the one thing to do now. Tap its button to do it.",
      "**Your journey** lists every step from booking to your photos, ticking off as each is done.",
      "**Plan** keeps everything in one list: your proposal, your agreement, **Payments**, your questionnaire and your timeline.",
      "**Messages** is a chat with your photographer, and **Files** holds anything they've shared with you.",
    ],
    next: "When your photographer needs something from you, you'll get an email with a link straight back here.",
    goodToKnow: ["**Your studio is on it** means there's nothing for you to do right now."],
    terms: ["couple-journey", "couple-retainer", "couple-final-balance"],
  },
  {
    id: "couple-proposal",
    title: "Choose your package and accept",
    summary: "Read your photographer's offer, pick your coverage, and accept it — or ask for changes.",
    audience: "couple",
    stage: "inquiry-to-booking",
    routes: ["/client/proposal", "/client/package"],
    purpose:
      "Your proposal is your photographer's offer: your package, any extras, the total and when each payment is due. Nothing is charged when you accept.",
    steps: [
      "If you're asked to **Choose your coverage**, tap a package, tick any **Add-ons** you want, then **Confirm**. Your price is fixed from then on.",
      "Open **Your proposal** and read **What's included** and the **Payment plan**.",
      "Happy with it? Tap **Accept proposal**, then **Confirm acceptance**.",
      "Something to change? Tap **Request changes**, say what you'd like, then **Send change request**.",
    ],
    next: "Your agreement comes next — by email, and under **Your agreement** here. Paying the retainer after you sign is the last step to reserve your date.",
    goodToKnow: [
      "Accepting doesn't sign anything or take a payment; those are separate, secure steps.",
      "Want something extra later? **Add to your booking** asks your studio, and they send you an updated proposal.",
      "If your studio sent one booking agreement instead, you accept by signing it: tap **Review & sign the agreement**.",
    ],
    terms: ["couple-retainer", "couple-final-balance"],
  },
  {
    id: "couple-sign",
    title: "Sign your agreement",
    summary: "Read your contract and sign it online with your typed name.",
    audience: "couple",
    stage: "inquiry-to-booking",
    routes: ["/client/contract"],
    video: "couple-sign",
    purpose:
      "Your agreement is your contract with your photographer. You read it and sign it right here; your typed name is your signature.",
    steps: [
      "Open **Your agreement** from the email, or from **Plan**.",
      "Read it through. Anything to change? Tap **Something to change? Ask before you sign**.",
      "Tap **Review & sign**, tick the box to sign electronically, and type your full name.",
      "Tap **Sign agreement**. If it comes in two parts — the terms, then your coverage and price — you type your name for each and tap **Sign both parts**.",
    ],
    next: "A signed copy is emailed to you, and **Download signed copy** keeps it here. The retainer invoice comes next; paying it reserves your date.",
    goodToKnow: [
      "If your studio changes your date or package later, you'll see **A change to sign** here. Your original agreement stands until you sign it.",
    ],
    terms: ["couple-agreement", "couple-booking-change", "couple-retainer"],
  },
  {
    id: "couple-pay",
    title: "Pay, and save a card for the final balance",
    summary: "See what's due, pay securely, and let the final balance pay itself.",
    audience: "couple",
    stage: "planning",
    routes: ["/client/payments"],
    purpose:
      "Your payments page shows every invoice for your booking and what's due next. You pay on your payment provider's own secure page; StudioCue never sees your card.",
    steps: [
      "Open **Your payments** from the email, or from **Plan**.",
      "Tap the pay button on what's due. Your invoice opens on Stripe's or QuickBooks' secure page.",
      "Come back here afterwards. The page checks for your payment by itself, or tap **Check payment status**.",
      "**Schedule** lists every invoice, soonest first, and which are paid.",
      "If you see **Pay your final balance automatically**, tap **Save a card** and your final balance is charged on its due date.",
    ],
    next: "Your studio sees your payment straight away. Paying the retainer reserves your date.",
    goodToKnow: [
      "A declined automatic charge is tried once more 3 days later. You can **Remove card** any time before.",
    ],
    terms: ["couple-retainer", "couple-final-balance", "couple-autopay"],
  },
  {
    id: "couple-questionnaire",
    title: "Fill in your questionnaire",
    summary: "Tell your photographer what they need to plan your day. Answers save as you go.",
    audience: "couple",
    stage: "planning",
    routes: ["/client/questionnaire"],
    purpose:
      "Your photographer uses your questionnaire to plan the day: the names, the timings and the moments that matter to you.",
    steps: [
      "Open **Your questionnaire** from the email, or from **Plan**.",
      "Answer section by section and tap **Next section**. Answers save as you type.",
      "Need a break? **Finish later: your answers are kept.**",
      "On the last step, **Review answers**, then **Send answers**. Required questions need an answer first.",
    ],
    next: "Your photographer has your answers straight away. To change one after sending, just message them.",
    goodToKnow: ["Some answers may already be filled in from what you told your photographer. You can change them."],
  },
  {
    id: "couple-day",
    title: "Your timeline, files and messages",
    summary: "Check your wedding-day timeline, message your photographer, and find every file.",
    audience: "couple",
    stage: "planning",
    routes: ["/client/schedule", "/client/messages", "/client/documents"],
    purpose:
      "As your wedding gets close, your timeline, your files and your messages with your photographer all live here.",
    steps: [
      "Open **Your timeline** from **Plan**. When it says **Ready for you to check**, look through the times.",
      "All good? Tap **Approve timeline**. Something off? Tap **Ask about this** on that time, or **Ask for changes**.",
      "**Messages** is a chat with your photographer; their replies come here and to your email. You can attach photos and files.",
      "**Files** keeps everything shared with you, plus your signed agreement and your invoices.",
    ],
    next: "Your photographer and crew plan the day from the version you approve. If it changes, you'll get a new version to check.",
    goodToKnow: [
      "Times are shown in the wedding's time zone.",
      "A week before the wedding you'll get an email with a link straight to your timeline.",
    ],
    terms: ["couple-timeline"],
  },
  {
    id: "couple-photos",
    title: "Get your photos",
    summary: "Open your gallery, save everything, approve your album and share a review.",
    audience: "couple",
    stage: "after-the-wedding",
    routes: ["/client/delivery", "/client/reviews"],
    purpose:
      "After the wedding, your photos — and your film, if it's part of your package — arrive here, with everything you need to open and keep them.",
    steps: [
      "Open **Your photos** from the email, or from **Plan**.",
      "Tap **Copy** beside the access code, then **Open your gallery** and paste it when it asks.",
      "Download and back everything up before access closes; the date is on the card. Then tap **I've downloaded everything**.",
      "Having an album? Choose photos in your gallery, tap **I've sent my selections**, then **Approve design** or **Ask for changes**.",
      "Loved it? **Would you share a few words?** links to your studio's review page. Tap **I've left my review** once you've posted it.",
    ],
    next: "Once you approve your album design, it's made exactly as shown.",
    goodToKnow: [
      "“I've downloaded everything” only tells your studio; it doesn't download anything or change your access.",
      "Access closed? Tap **Ask for access**.",
    ],
  },

  // ── Crew ──────────────────────────────────────────────────────────────
  {
    id: "crew-tour",
    title: "Find your jobs and accept offers",
    summary: "Offers, your schedule and everything for the day, on your phone.",
    audience: "crew",
    stage: "getting-started",
    routes: ["/crew", "/crew/**"],
    purpose:
      "This is where a studio sends you work. Offers, your schedule and everything for the day are here, made for your phone.",
    steps: [
      "New offers appear on **Today**. Open one for the date, the job and the fee.",
      "Tap **Accept**, or **Decline offer** and tell the studio why.",
      "**Jobs** lists the jobs you've accepted. Open one to prep: read the checklist and send anything the studio asks for.",
      "On the day, **Open the day sheet** for where to be and when, your role, who to call and the running order.",
      "**Calendar** is where you mark the dates you're not free; **Me** holds your profile.",
    ],
    next: "After the event, send your hours and expenses from the job so the studio can pay you.",
    goodToKnow: ["Questions about a job? **Message the studio** from the job itself."],
    terms: ["crew-offer-crew", "day-sheet"],
  },
  {
    id: "crew-offer-accept",
    title: "Accept or decline a job",
    summary: "Everything you need to decide on an offer, and how to answer it.",
    audience: "crew",
    stage: "every-day",
    routes: ["/crew/pending"],
    video: "crew-offer-accept",
    purpose: "An offer is a studio asking you to work a date. Everything you need to decide is in the offer itself.",
    steps: [
      "Open the offer from the email, or from **Today**.",
      "Check the date and times, the fee and **What you'd do**.",
      "Answer before the **Answer by** time; after that the offer closes and the studio may ask someone else.",
      "Tap **Accept**. Or tap **Decline**, pick a reason if you like, and tap **Decline offer**.",
    ],
    next: "An accepted job moves to **Jobs**, and its day sheet appears once the studio shares the run of show. **Add to my calendar** saves the date.",
    goodToKnow: ["Your reason for declining is optional. It just tells the studio whether it was the date, the fee or the job."],
    terms: ["crew-offer-crew"],
  },
  {
    id: "crew-day",
    title: "Prep and your day sheet",
    summary: "What the studio needs before the day, and everything to work from on it.",
    audience: "crew",
    stage: "planning",
    routes: ["/crew/jobs", "/crew/prep", "/crew/schedule"],
    purpose:
      "Before the day, the job page tells you what the studio needs from you. On the day, your day sheet has everything to work from.",
    steps: [
      "Open **Jobs** and pick the job. The **Checklist** lists what the studio needs: paperwork, gear and the run of show.",
      "Send documents with **Take a photo** or **Choose a file**. The studio checks each one.",
      "Confirm gear with **I'll bring it**, and notes with **Got it**.",
      "Open the **Day sheet**: **Where**, **Who to call**, **Your role** and the **Running order**.",
      "At the bottom, tap **I've read version** so the studio knows you've read the latest.",
    ],
    next: "If the studio changes the run of show, the version number goes up and you'll be asked to confirm again.",
    goodToKnow: [
      "Two days before, you'll get an email with your call time, where to be and a link to the day sheet.",
      "The day sheet is saved on your phone, so it opens with no signal.",
      "Only your own paperwork is here. You never see the couple's contract, invoices or photos.",
    ],
    terms: ["call-time", "crew-checklist", "day-sheet"],
  },
  {
    id: "crew-closeout",
    title: "Send your hours and expenses",
    summary: "After a job, tell the studio your hours, costs and file links so they can pay you.",
    audience: "crew",
    stage: "after-the-wedding",
    routes: ["/crew/closeout"],
    purpose: "After a job, send your hours, expenses and links to your files so the studio can pay you.",
    steps: [
      "Open **Hours and expenses** from the job, or from **Today**.",
      "Check **Started** and **Finished**. Add **Extra time** only if you worked past the agreed wrap.",
      "Add costs with **Add an expense**, and links to your files with **Add a link**.",
      "Tap **Send to the studio**.",
    ],
    next: "The studio reviews it and schedules your payment; the date shows here. If they need a fix you'll see **Changes asked** with their note — update it and send again.",
    goodToKnow: ["Links need to start with https://.", "Travel and setup count as extra time only if the studio said so."],
    terms: ["crew-closeout"],
  },
  {
    id: "crew-availability",
    title: "Your availability and profile",
    summary: "Tell studios when you can work, and keep your details and papers up to date.",
    audience: "crew",
    stage: "admin",
    routes: ["/crew/availability", "/crew/account"],
    purpose: "Tell studios when you can work, and keep your profile and papers up to date so they can offer you jobs.",
    steps: [
      "Open **Calendar** and tap a day. Choose **I'm free**, **Maybe** or **I'm away**, then **Save**.",
      "To mark a run of days, fill in **Through (optional)**.",
      "In **Me**, fill in **Your work** — what you shoot, where, and your gear — and your **Contact** details.",
      "Under **Your papers**, send your **W-9** and **Certificate of insurance**.",
      "Tap **Save changes**.",
    ],
    next: "Studios see your dates when they staff a job. Marking a day never books you; only accepting an offer does.",
  },
];

const byId = new Map(EXPLAINERS.map((guide) => [guide.id, guide]));

export function explainer(id: string): Explainer | undefined {
  return byId.get(id);
}
