import type { LegalDocument } from "../document-types";
import { LEGAL_ENTITY, TERMS_EFFECTIVE, TERMS_VERSION } from "../legal";

const { name, addressOneLine, email } = LEGAL_ENTITY;

export const TERMS_OF_SERVICE: LegalDocument = {
  slug: "terms",
  path: "/terms",
  title: "Terms of Service",
  description:
    "The agreement that governs a business's subscription to and use of StudioCue: trial, billing, renewal, cancellation, data, AI, electronic signatures, liability and disputes.",
  version: TERMS_VERSION,
  effective: TERMS_EFFECTIVE,
  intro: [
    `These Terms of Service (the “Terms”) form a binding agreement between ${name}, a New Jersey limited liability company that operates StudioCue (“StudioCue,” “we,” “us” or “our”), and the business that creates a StudioCue account or uses the Service (“Customer,” “you” or “your”).`,
    "Please read these Terms carefully. Section 7 explains that your subscription renews automatically until you cancel. Section 29 limits our liability. Section 31 contains a waiver of jury trial and of class actions. By creating an account, clicking to accept, or using the Service, you agree to these Terms on behalf of your business. If you do not agree, do not use the Service.",
  ],
  sections: [
    {
      id: "agreement",
      title: "1. The agreement",
      blocks: [
        { p: "These Terms incorporate, and you also agree to, the following documents, each as updated from time to time: the [Privacy Policy](/privacy), the [Data Processing Addendum](/legal/dpa), the [Acceptable Use Policy](/legal/acceptable-use), the [Cookie and Browser Storage Notice](/legal/cookies) and the plan details shown on the [Pricing](/pricing) page and at checkout (together, the “Agreement”)." },
        { p: "If there is a conflict between documents, the following order applies, highest first: (a) the Data Processing Addendum, as to the processing of Client Data; (b) these Terms; (c) the Acceptable Use Policy; (d) the plan details; and (e) any other referenced policy. An order form or written agreement signed by both parties that expressly states it overrides these Terms will control for the matters it covers." },
      ],
    },
    {
      id: "definitions",
      title: "2. Definitions",
      blocks: [
        { list: [
          "**“Service”** means StudioCue’s hosted software, websites, portals, mobile web experiences, APIs, AI features and related support, as made available by us from time to time.",
          "**“Account”** means the workspace created for your business, including any additional branded businesses included in your plan.",
          "**“Account Owner”** means the person who created the Account or to whom ownership has been transferred, who has authority to bind Customer.",
          "**“Team Member”** means an employee, contractor or other person you authorize to use the Service as part of your internal team (for example an administrator, coordinator or lead photographer).",
          "**“Invited User”** means a person you invite to use a limited part of the Service for your business, such as your clients, their partners or family members, crew members, second shooters, planners and vendors.",
          "**“Customer Data”** means all data, content and files that you, your Team Members or your Invited Users submit to or create in the Service, including Client Data, but excluding Usage Data.",
          "**“Client Data”** means personal information within Customer Data relating to your clients, Invited Users, crew, vendors or other individuals with whom you do business.",
          "**“Customer Agreement”** means any proposal, contract, agreement, amendment, questionnaire, invoice or other document between you and your client or another third party that is prepared, sent or signed through the Service.",
          "**“AI Output”** means drafts, suggestions, summaries, schedules, extractions and other content generated by the Service’s artificial-intelligence features.",
          "**“Usage Data”** means data about how the Service is used and performs (such as feature use, error reports, logs and performance metrics) that does not identify you, your users or any individual, or that has been de-identified or aggregated.",
          "**“Third-Party Service”** means any product or service not provided by us that you connect to or use with the Service, such as Google Calendar, Zoom, QuickBooks Online, Dropbox or your email provider.",
          "**“Subscription Term”** means the trial period and each monthly or annual billing period during which you have access to the Service.",
        ] },
      ],
    },
    {
      id: "eligibility",
      title: "3. Eligibility and authority",
      blocks: [
        { p: "The Service is offered only to businesses, including sole proprietors acting in a business capacity. It is not intended for personal, family or household use. You represent that: (a) you are at least 18 years old; (b) you have authority to bind the business on whose behalf you accept these Terms; (c) the information you provide when registering is accurate and complete; and (d) you are not located in, or owned or controlled by a person located in, a country or region subject to comprehensive U.S. sanctions, and you are not on any U.S. government list of restricted parties." },
        { p: "We may refuse service, or close an Account, where we reasonably believe these requirements are not met." },
      ],
    },
    {
      id: "accounts",
      title: "4. Accounts, users and security",
      blocks: [
        { list: [
          "**Account Owner.** The Account Owner controls the Account, including billing, Team Member access, integrations, data export and closure. You may transfer ownership to another Team Member through the Service or by written request from the current Account Owner.",
          "**Team Members.** Each plan includes a maximum number of Team Members and crew profiles, shown on the Pricing page. Each Team Member must have their own login; sharing credentials is not permitted. You are responsible for assigning appropriate roles and permissions and for removing access promptly when a person leaves your business.",
          "**Responsibility for users.** You are responsible for all activity under your Account, including the acts and omissions of your Team Members and of Invited Users acting on your instructions, as if they were your own.",
          "**Security of credentials.** You must keep login credentials confidential, use a strong password or a supported single-sign-on provider, and notify us immediately at [support@studio-cue.com](mailto:support@studio-cue.com) if you suspect unauthorized access. We are not liable for losses caused by unauthorized use of credentials that results from your failure to keep them secure.",
          "**Accurate information.** You must keep your business name, contact details, billing information and the Account Owner’s email address current. Notices we send to that email address are effective when sent.",
        ] },
      ],
    },
    {
      id: "service",
      title: "5. The Service and your plan",
      blocks: [
        { p: "Subject to the Agreement and payment of applicable fees, we grant you a non-exclusive, non-transferable, non-sublicensable right during the Subscription Term to access and use the Service, and to permit your Team Members and Invited Users to do so, solely for your internal business operations." },
        { list: [
          "**Plans and limits.** Your plan determines the features available to you and usage limits such as the number of Team Members, crew profiles, branded businesses and monthly AI actions. Limits are described on the Pricing page and in the Service. If you exceed a limit, we may ask you to upgrade, and some features may pause until the next billing period or until you upgrade.",
          "**AI action allowance.** Each plan includes a monthly allowance of AI actions. Unused allowance does not carry over. Additional usage may be offered as an add-on at the price shown in the Service.",
          "**Add-ons.** Optional add-ons, such as additional users, brands or usage, are billed as described when you purchase them and renew with your subscription unless removed.",
          "**Beta features.** Features we label as preview, beta or early access are provided “as is,” may change or be withdrawn at any time and are excluded from any commitments in these Terms.",
        ] },
      ],
    },
    {
      id: "trial",
      title: "6. Free trial",
      blocks: [
        { p: "New Customers may be offered a free trial (currently 14 days). A valid payment card is required to start a trial. You will not be charged during the trial. One free trial is available per business; we may decline a trial, or charge from the outset, where we reasonably believe a business has already used one." },
        { p: "**When your trial ends, your paid subscription begins automatically** and the card on file is charged the then-current price of the plan and billing interval you selected, unless you cancel before the trial ends. We will show the date the trial ends and the amount that will be charged before you start the trial, and in Settings → Plan & billing throughout the trial." },
      ],
    },
    {
      id: "billing",
      title: "7. Fees, billing and automatic renewal",
      blocks: [
        { list: [
          "**Fees.** You agree to pay the fees for your plan and any add-ons at the prices shown on the Pricing page or at checkout when you subscribe, as updated under this Section.",
          "**Automatic renewal.** Your subscription renews automatically at the end of each monthly or annual billing period for a period of the same length, and you authorize us to charge the payment method on file for each renewal at the then-current price, **until you cancel**. You can cancel at any time as described in Section 8.",
          "**Billing in advance.** Fees are billed in advance at the start of each billing period. Upgrades take effect immediately and are prorated for the remainder of the current period; downgrades take effect at the next renewal.",
          "**Payment processing.** Payments are processed by our payment processor, Stripe, Inc., subject to its terms. StudioCue does not receive or store full payment-card numbers. You authorize us and Stripe to store your payment method and to charge it as described in these Terms, and to update it with information from your card issuer where permitted.",
          "**Price changes.** We may change our prices. We will give the Account Owner at least 30 days’ notice by email before a price increase applies to you. The new price takes effect at your first renewal after the notice period. If you do not agree, you may cancel before that renewal.",
          "**Receipts and invoices.** Receipts and invoices are available through the billing portal in Settings → Plan & billing.",
          "**Currency.** Fees are stated and charged in U.S. dollars unless we state otherwise at checkout.",
        ] },
      ],
    },
    {
      id: "cancellation",
      title: "8. Cancellation and refunds",
      blocks: [
        { list: [
          "**How to cancel.** The Account Owner can cancel at any time online in Settings → Plan & billing, without contacting us. You may also cancel by emailing [support@studio-cue.com](mailto:support@studio-cue.com) from the Account Owner’s email address; we will confirm cancellation in writing.",
          "**Effect of cancellation.** Cancellation stops the next renewal. Your access continues until the end of the billing period you have already paid for, after which the Account becomes read-only for the data-export period described in Section 27.",
          "**Cancelling during a trial.** If you cancel before the trial ends, you will not be charged.",
          "**Refunds.** Except as stated in this Section or required by law, fees are non-refundable and we do not provide refunds or credits for partial billing periods, unused time, unused allowances or downgrades.",
          "**Annual plans — 14-day refund.** If you cancel an annual plan within 14 days after the first charge for that annual plan (not a renewal), we will refund that charge in full on request to [support@studio-cue.com](mailto:support@studio-cue.com).",
          "**Our termination without cause.** If we terminate your subscription for convenience under Section 27, we will refund any prepaid fees for the unused remainder of the then-current billing period.",
        ] },
      ],
    },
    {
      id: "taxes",
      title: "9. Taxes",
      blocks: [
        { p: "Fees exclude taxes. You are responsible for all sales, use, value-added, goods and services and similar taxes, duties and levies associated with your purchase, other than taxes on our net income. Where we are required by law to collect taxes, we will add them to your invoice unless you provide a valid exemption certificate." },
      ],
    },
    {
      id: "late-payment",
      title: "10. Failed payments and suspension",
      blocks: [
        { p: "If a payment fails, we and Stripe may retry the charge and will notify the Account Owner. You agree to update your payment method promptly." },
        { list: [
          "**Grace period.** For 7 days after a failed renewal payment, you will continue to have full access, with a notice in the Service.",
          "**Read-only access.** If the amount remains unpaid after the grace period, we may restrict the Account to read-only access: you and your Team Members can view and export Customer Data but cannot send communications, create or send documents or invoices, or start new automations. Communications and automations that would otherwise run on your behalf are paused and held, and resume when the Account is brought current.",
          "**Cancellation for non-payment.** If the amount remains unpaid after our payment retries are exhausted, your subscription may be cancelled and the Account treated as terminated under Section 27.",
          "**Disputed charges.** If you believe a charge is wrong, contact us within 60 days of the charge. Initiating a chargeback without first contacting us may result in suspension while the dispute is resolved.",
        ] },
      ],
    },
    {
      id: "customer-data",
      title: "11. Customer Data",
      blocks: [
        { list: [
          "**Ownership.** As between you and us, you own all Customer Data. We do not acquire any ownership rights in Customer Data.",
          "**License to us.** You grant us a worldwide, non-exclusive, royalty-free license to host, copy, store, transmit, process, display and otherwise use Customer Data only as necessary to provide, maintain, secure and support the Service for you; to prevent or address technical, security or fraud issues; to comply with law; and as you otherwise instruct through the Service.",
          "**Usage Data.** We may collect and use Usage Data to operate, analyze, secure and improve the Service and to develop new features. We will not use Usage Data in a way that identifies you, your users or any individual to a third party, except as required by law.",
          "**Your responsibility for Customer Data.** You are solely responsible for the accuracy, quality, legality and appropriateness of Customer Data and for having all rights, licenses, notices and consents needed for us to process it under the Agreement.",
          "**No sale.** We do not sell Customer Data or Client Data, and we do not share it with third parties for their own advertising or marketing.",
          "**Export.** You may export Customer Data at any time during the Subscription Term, and during the export period after termination, using the export tools in Settings → Data & account.",
        ] },
      ],
    },
    {
      id: "data-protection",
      title: "12. Data protection and privacy",
      blocks: [
        { p: "Our collection and use of personal information about you and your Team Members as our own customers is described in the [Privacy Policy](/privacy)." },
        { p: "For Client Data, you are the business (or controller) that determines the purposes and means of processing, and we are your service provider (or processor). Our processing of Client Data is governed by the [Data Processing Addendum](/legal/dpa), which forms part of these Terms and which you accept by accepting these Terms. Among other things, the Data Processing Addendum requires us to process Client Data only on your documented instructions, to keep it confidential and secure, to use only the subprocessors listed on our [Subprocessors](/subprocessors) page, to assist you with individuals’ requests, and to notify you of a personal-data breach without undue delay." },
      ],
    },
    {
      id: "customer-responsibilities",
      title: "13. Your responsibilities and compliance with law",
      blocks: [
        { p: "You are responsible for your use of the Service and for your business’s compliance with all laws that apply to it, including:" },
        { list: [
          "providing any privacy notices to, and obtaining any consents from, your clients, Invited Users, crew and other individuals that are required for you to collect their information and for us to process it on your behalf;",
          "laws governing commercial and transactional communications, including the CAN-SPAM Act and, where you send text messages, the Telephone Consumer Protection Act and state equivalents;",
          "consumer-protection, contract, automatic-renewal, deposit and cancellation laws that apply to your agreements and dealings with your clients;",
          "employment, independent-contractor, tax and insurance laws that apply to your crew and your business;",
          "laws relating to photography, recording and releases, including the rights of minors and of people who appear in your work; and",
          "keeping any records you are legally required to keep. The Service is not a substitute for your own record-keeping obligations.",
        ] },
        { p: "You must not upload to the Service government identification numbers (such as Social Security numbers or driver’s-license numbers), full payment-card or bank-account numbers, health or medical information, biometric identifiers, or information about criminal history, except as a necessary part of an insurance certificate or similar document that the Service is designed to handle. The Service is not designed to meet the requirements of laws governing such information, such as HIPAA or PCI DSS, and you must not use it for that purpose." },
      ],
    },
    {
      id: "acceptable-use",
      title: "14. Acceptable use",
      blocks: [
        { p: "You must comply, and ensure your Team Members and Invited Users comply, with our [Acceptable Use Policy](/legal/acceptable-use). In summary, you must not use the Service to break the law; send spam or deceptive communications; infringe others’ rights; upload malware; access other customers’ data; probe, test or disrupt the Service without our written permission; reverse-engineer it except as permitted by law; resell it; or circumvent plan limits. We may investigate suspected violations and take the actions described in the Acceptable Use Policy and in Section 27." },
      ],
    },
    {
      id: "ai",
      title: "15. AI features",
      blocks: [
        { list: [
          "**How they work.** The Service includes features that use artificial intelligence to draft replies, proposals and messages, summarize inquiries and consultations, propose schedules, extract information from documents and answer questions about your Account. These features run on Google’s Gemini models through Google Cloud Vertex AI within our own Google Cloud project. We do not send Customer Data to any other AI provider.",
          "**Human review required.** AI Output may be inaccurate, incomplete, out of date or inappropriate. AI Output is a draft for your review. You are responsible for reviewing, editing and approving any AI Output before you rely on it or send it to anyone, and for the consequences of doing so. The Service is designed so that AI never sends client-facing communications, signs documents, records payments, changes permissions or marks work complete without a person’s approval.",
          "**No professional advice.** AI Output is not legal, tax, accounting, insurance or other professional advice.",
          "**No training on your data.** We do not use Customer Data, Client Data or AI Output to train or fine-tune artificial-intelligence models, and our AI provider does not use them to train its models.",
          "**Ownership.** As between you and us, AI Output generated from your Customer Data is Customer Data. Similar output may be generated for other customers, and you acquire no exclusive rights in output that is not specific to your Customer Data.",
          "**Allowance.** Use of AI features counts toward your plan’s AI action allowance (Section 5).",
        ] },
      ],
    },
    {
      id: "esign",
      title: "16. Electronic signatures and Customer Agreements",
      blocks: [
        { p: "The Service lets you prepare Customer Agreements and have them signed electronically by you and your clients. Electronic signatures applied through the Service are designed to satisfy the U.S. Electronic Signatures in Global and National Commerce Act (15 U.S.C. § 7001 et seq.) and state laws adopting the Uniform Electronic Transactions Act. Before signing, each client is shown, and must accept, our [Electronic Signature Disclosure and Consent](/legal/esign). For each signature, the Service records the signer’s typed name, the email address with which the signer is authenticated, the date and time, the signer’s IP address and device information, the version of the consent accepted and a cryptographic fingerprint of the exact document signed, and attaches that record to the signed document." },
        { list: [
          "**You are the contracting party.** Each Customer Agreement is solely between you and your client or other counterparty. StudioCue is not a party to, and is not responsible for the performance or enforcement of, any Customer Agreement.",
          "**No legal advice; your content.** We do not review or approve the content of Customer Agreements. Any template, clause, schedule or sample text we provide is for convenience only, is not legal advice and may not be suitable for your business or jurisdiction. You are solely responsible for the content of your Customer Agreements and for their legality and enforceability, including compliance with consumer-protection, deposit, refund, cancellation and disclosure laws. You should have your agreements reviewed by a lawyer licensed in your jurisdiction.",
          "**Documents that must not be signed electronically.** You must not use the Service for documents that the law does not permit to be signed electronically or that require notarization, witnessing or a specific form of delivery that the Service does not provide.",
          "**Records.** Signed Customer Agreements and their signature records are retained in your Account and are subject to Section 27 on termination. You are responsible for retaining your own copies for as long as you need them.",
        ] },
      ],
    },
    {
      id: "payments",
      title: "17. Invoices, payments and accounting services",
      blocks: [
        { p: "The Service can create, send and track invoices and record payments through accounting and payment services that you connect, such as QuickBooks Online and QuickBooks Payments. StudioCue is not a bank, payment processor, payment facilitator or money transmitter, and never receives, holds or transmits funds paid by your clients. Payments are processed by the provider you connect, under its terms, and are deposited directly with you." },
        { list: [
          "You are solely responsible for your prices, deposits, retainers, payment schedules, taxes, refunds and invoice settings, and for resolving any payment dispute, chargeback or refund request with your clients.",
          "Amounts, due dates and tax calculations shown in the Service depend on your settings and on information from the connected provider. You should review invoices before sending them.",
          "If you enable automatic payment, you are responsible for obtaining your client’s authorization in the form required by law and by your payment provider.",
        ] },
      ],
    },
    {
      id: "third-party",
      title: "18. Third-Party Services and integrations",
      blocks: [
        { p: "The Service may let you connect Third-Party Services. When you connect one, you authorize us to access, retrieve, store and transmit data in that Third-Party Service on your behalf as needed to provide the connected features, using the permissions you grant. Your use of each Third-Party Service is governed by its own terms and privacy policy, and its provider, not us, is responsible for it." },
        { p: "We do not warrant or support Third-Party Services, and we are not responsible for their availability, accuracy, security or changes, or for any data loss or charges arising from them. If a Third-Party Service changes or discontinues its interface, we may modify or discontinue the related integration without liability. You may disconnect an integration at any time in Settings → Integrations, which stops our further access to that Third-Party Service." },
      ],
    },
    {
      id: "communications",
      title: "19. Communications sent through the Service",
      blocks: [
        { p: "The Service sends email and other communications to your clients, Invited Users and crew on your behalf and under your business name. You are the sender of those communications for legal purposes and are responsible for their content, their recipients and your compliance with applicable law, including identifying your business and including a valid postal address where the law requires." },
        { list: [
          "You may send only transactional and relationship communications relating to work you have been engaged for or inquiries you have received, or other communications that recipients have agreed to receive. You must not use the Service for bulk marketing to people who have not asked to hear from you.",
          "We may decline to send, delay or suppress messages to addresses that have bounced, complained or unsubscribed, or that we reasonably believe would harm the deliverability or reputation of the Service.",
          "We do not guarantee delivery of any communication. Delivery depends on recipients’ email providers and other factors outside our control.",
        ] },
      ],
    },
    {
      id: "minors",
      title: "20. Minors",
      blocks: [
        { p: "Accounts and Team Member access are for adults only. The Service does not create accounts for children, does not send communications to children and does not use facial recognition. Where your work involves minors — for example, family sessions, school events or youth sports — the parent, legal guardian or responsible organization must be your client and the recipient of all communications. You are responsible for obtaining any consents, releases and authorizations required by law for photographing minors and for processing their information, and for entering only the minimum information about a minor that your work requires." },
      ],
    },
    {
      id: "invited-users",
      title: "21. Invited Users",
      blocks: [
        { p: "Invited Users access the Service at your invitation and for your business. Their use is subject to our [Client and Crew Terms](/legal/client-terms). You are responsible for the invitations you send, for the information you share with each Invited User, and for removing access when it is no longer appropriate. Your relationship with each Invited User, including any services you provide to them or they provide to you, is solely between you and them." },
      ],
    },
    {
      id: "confidentiality",
      title: "22. Confidentiality",
      blocks: [
        { p: "Each party may receive non-public information from the other that is marked confidential or that a reasonable person would understand to be confidential (“Confidential Information”). Customer Data is your Confidential Information. Non-public features, pricing, security information and documentation of the Service are our Confidential Information." },
        { p: "The receiving party will use the other party’s Confidential Information only to perform under or exercise its rights under the Agreement, will protect it using at least reasonable care, and will disclose it only to its employees, contractors and service providers who need to know it and are bound by confidentiality obligations at least as protective as these. Confidential Information does not include information that is or becomes public through no fault of the recipient, was known to the recipient without restriction, is independently developed, or is rightfully received from a third party without restriction. A party may disclose Confidential Information when required by law, after giving the other party reasonable notice where legally permitted." },
      ],
    },
    {
      id: "security",
      title: "23. Security",
      blocks: [
        { p: "We maintain administrative, technical and physical safeguards designed to protect Customer Data, as described in the [Data Processing Addendum](/legal/dpa). These include encryption in transit and at rest, logical separation of each customer’s data, role-based access controls, least-privilege access for our personnel, secret management for integration credentials, audit logging, backups and monitoring. No system is completely secure, and we do not guarantee that unauthorized access will never occur. You are responsible for the security of your devices, your credentials and the systems you connect to the Service, and for configuring user permissions appropriately." },
      ],
    },
    {
      id: "ip",
      title: "24. Intellectual property and feedback",
      blocks: [
        { list: [
          "**Our rights.** The Service, including its software, design, text, graphics, templates, starter content, documentation and our trademarks, is owned by us or our licensors and is protected by intellectual-property laws. Except for the limited rights expressly granted in these Terms, we reserve all rights. Nothing in the Agreement transfers ownership of the Service to you.",
          "**Templates.** You may use, copy and adapt templates and starter content we provide within the Service for your own business. You may not resell or redistribute them as standalone products.",
          "**Feedback.** If you give us suggestions or feedback, you grant us a perpetual, irrevocable, royalty-free license to use them without restriction or compensation. We will not identify you as their source without your permission.",
          "**Publicity.** We will not use your business name or logo to identify you as a customer without your prior consent.",
          "**Copyright complaints.** We respond to notices of alleged copyright infringement as described in our [Copyright Policy](/legal/copyright).",
        ] },
      ],
    },
    {
      id: "availability",
      title: "25. Availability, support and maintenance",
      blocks: [
        { p: "We use commercially reasonable efforts to make the Service available 24 hours a day, 7 days a week, except for planned maintenance, emergency maintenance, and events beyond our reasonable control. We will try to schedule planned maintenance to minimize disruption and to give advance notice of planned maintenance expected to cause significant downtime. We do not offer a service-level agreement or service credits unless agreed in a signed writing." },
        { p: "Support is available by email at [support@studio-cue.com](mailto:support@studio-cue.com) and through the in-app help and feedback tools. We aim to respond within one business day." },
      ],
    },
    {
      id: "changes-to-service",
      title: "26. Changes to the Service",
      blocks: [
        { p: "We continually develop the Service and may add, modify or remove features. We will not materially reduce the core functionality of your plan during a billing period you have paid for. If we remove a core feature of your plan, we will notify the Account Owner in advance; if you cancel because of that change within 30 days of the notice, we will refund prepaid fees for the unused remainder of the current billing period." },
      ],
    },
    {
      id: "termination",
      title: "27. Term, termination and your data",
      blocks: [
        { p: "The Agreement begins when you create an Account and continues until all subscriptions have ended and the export period has expired." },
        { list: [
          "**Termination by you.** You may cancel at any time under Section 8.",
          "**Termination for cause.** Either party may terminate the Agreement on written notice if the other party materially breaches it and does not cure the breach within 30 days after notice (10 days for non-payment).",
          "**Suspension.** We may suspend all or part of your access immediately, with notice where practicable, if: your use poses a security risk to the Service or others; you or your users violate the Acceptable Use Policy; we are required to do so by law or a government authority; or payment is overdue as described in Section 10. We will limit any suspension to the extent reasonably necessary and restore access promptly once the issue is resolved.",
          "**Termination for convenience by us.** We may terminate the Agreement for any reason on 60 days’ written notice to the Account Owner, in which case Section 8 provides for a refund of prepaid fees.",
          "**Export period.** After your subscription ends for any reason other than our termination for your material breach or unlawful use, your Account will remain available in read-only mode for 30 days so the Account Owner can export Customer Data.",
          "**Deletion.** After the export period, we will delete Customer Data from the active Service. Residual copies in our backups are overwritten in the ordinary course and in any event within 90 days. We may retain information that we are required by law to keep (such as our billing records), information needed to resolve disputes or enforce the Agreement, and the signature records and audit logs described in the Privacy Policy for the periods stated there, all subject to the confidentiality obligations of these Terms.",
          "**Survival.** Sections 7 (as to amounts owed), 8, 9, 11 (as to export and Usage Data), 13, 16 (as to responsibility for Customer Agreements), 17, 22, 24, 27, 28, 29, 30, 31, 33 and 35, and any other provision that by its nature should survive, survive termination.",
        ] },
      ],
    },
    {
      id: "warranties",
      title: "28. Warranties and disclaimers",
      blocks: [
        { p: "We warrant that, during the Subscription Term, the Service will perform materially as described in our then-current documentation and that we will not materially decrease the overall security of the Service. Your exclusive remedy for breach of this warranty is for us to use reasonable efforts to correct the non-conformity or, if we cannot do so within a reasonable time, for you to terminate the affected subscription and receive a refund of prepaid fees for the unused remainder of the current billing period." },
        { p: "EXCEPT AS EXPRESSLY STATED IN THESE TERMS, THE SERVICE, AI OUTPUT, TEMPLATES AND ALL RELATED MATERIALS ARE PROVIDED “AS IS” AND “AS AVAILABLE.” TO THE FULLEST EXTENT PERMITTED BY LAW, WE AND OUR LICENSORS DISCLAIM ALL OTHER WARRANTIES, EXPRESS, IMPLIED OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT AND ACCURACY, AND ANY WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE OF TRADE. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT ANY COMMUNICATION WILL BE DELIVERED, OR THAT READINESS CHECKS, REMINDERS, SCHEDULES OR AI OUTPUT WILL BE COMPLETE OR CORRECT. THE SERVICE DOES NOT PROVIDE LEGAL, TAX, ACCOUNTING OR INSURANCE ADVICE." },
      ],
    },
    {
      id: "liability",
      title: "29. Limitation of liability",
      blocks: [
        { p: "TO THE FULLEST EXTENT PERMITTED BY LAW:" },
        { ordered: [
          "NEITHER PARTY WILL BE LIABLE TO THE OTHER FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, REVENUE, BOOKINGS, BUSINESS, GOODWILL OR ANTICIPATED SAVINGS, OR FOR ANY LOSS OR CORRUPTION OF DATA, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.",
          "EACH PARTY’S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THE AGREEMENT OR THE SERVICE WILL NOT EXCEED THE TOTAL FEES PAID AND PAYABLE BY YOU TO US FOR THE SERVICE IN THE TWELVE (12) MONTHS IMMEDIATELY BEFORE THE EVENT GIVING RISE TO THE LIABILITY, OR ONE HUNDRED U.S. DOLLARS (US $100) IF NO FEES WERE PAYABLE.",
          "THE LIMITATIONS IN THIS SECTION DO NOT APPLY TO: YOUR OBLIGATION TO PAY FEES; YOUR INDEMNIFICATION OBLIGATIONS; EITHER PARTY’S LIABILITY FOR ITS GROSS NEGLIGENCE, WILLFUL MISCONDUCT OR FRAUD; OR LIABILITY THAT CANNOT BE LIMITED UNDER APPLICABLE LAW.",
        ] },
        { p: "The parties agree that these limitations are an essential basis of the bargain and that the fees reflect this allocation of risk." },
      ],
    },
    {
      id: "indemnification",
      title: "30. Indemnification",
      blocks: [
        { list: [
          "**By you.** You will defend, indemnify and hold harmless StudioCue, its members, officers, employees and agents from and against any third-party claim, and all resulting damages, losses, fines, penalties, costs and reasonable attorneys’ fees, arising out of or relating to: (a) Customer Data, including any claim that it infringes or violates a third party’s rights or that you lacked a necessary notice or consent; (b) your Customer Agreements and your services to, and dealings with, your clients, crew and vendors; (c) communications sent through the Service on your behalf; or (d) your or your users’ violation of the Agreement or of applicable law.",
          "**By us.** We will defend you against any third-party claim alleging that the Service, as provided by us and used in accordance with the Agreement, infringes a United States patent, copyright or trademark or misappropriates a trade secret, and will pay damages finally awarded or agreed in settlement. We have no obligation for claims arising from Customer Data, Third-Party Services, AI Output you modify or use outside the Service, combinations with items we did not provide, or use in violation of the Agreement. If the Service is, or we believe it is likely to be, subject to such a claim, we may procure the right for you to continue using it, modify it to be non-infringing, or terminate the affected subscription and refund prepaid fees for the unused remainder of the current billing period. This paragraph states our entire liability for infringement claims.",
          "**Procedure.** The indemnified party must give prompt written notice of the claim, allow the indemnifying party to control its defense and settlement (except that no settlement may impose an obligation on the indemnified party without its consent, not to be unreasonably withheld), and provide reasonable cooperation at the indemnifying party’s expense.",
        ] },
      ],
    },
    {
      id: "disputes",
      title: "31. Governing law and disputes",
      blocks: [
        { list: [
          "**Informal resolution.** Before filing a claim, each party agrees to try to resolve the dispute informally by written notice to the other (to us at [support@studio-cue.com](mailto:support@studio-cue.com) and the postal address in Section 33). If the dispute is not resolved within 30 days after notice, either party may proceed under this Section.",
          "**Governing law.** The Agreement and any dispute arising out of or relating to it or the Service are governed by the laws of the State of New Jersey, without regard to its conflict-of-laws rules. The United Nations Convention on Contracts for the International Sale of Goods does not apply.",
          "**Venue.** Any action must be brought exclusively in the state courts located in Morris County, New Jersey, or the United States District Court for the District of New Jersey, and each party consents to the personal jurisdiction of those courts. Either party may instead bring an individual claim in a small-claims court of competent jurisdiction.",
          "**Injunctive relief.** Either party may seek injunctive or other equitable relief in any court of competent jurisdiction to protect its intellectual property or Confidential Information.",
          "**Waiver of jury trial.** TO THE FULLEST EXTENT PERMITTED BY LAW, EACH PARTY WAIVES ANY RIGHT TO A JURY TRIAL IN ANY ACTION ARISING OUT OF OR RELATING TO THE AGREEMENT OR THE SERVICE.",
          "**No class actions.** TO THE FULLEST EXTENT PERMITTED BY LAW, EACH PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, CONSOLIDATED OR REPRESENTATIVE PROCEEDING.",
          "**Time to bring claims.** Any claim must be brought within one year after the cause of action arises, except claims for non-payment of fees or for infringement of intellectual-property rights, or where a longer period is required by law.",
        ] },
      ],
    },
    {
      id: "export",
      title: "32. Export controls and sanctions",
      blocks: [
        { p: "You will comply with all applicable export-control and sanctions laws in using the Service. You will not use, or permit the use of, the Service in or for the benefit of any country, region or person subject to U.S. sanctions or export restrictions." },
      ],
    },
    {
      id: "notices",
      title: "33. Notices",
      blocks: [
        { p: `We may give notices by email to the Account Owner’s email address, by notice in the Service, or by post to the address you provide. You may give notices to us by email to [support@studio-cue.com](mailto:support@studio-cue.com), with legal notices also sent by post or courier to ${name}, Attn: Legal, ${addressOneLine}. Notices are effective when sent by email, when posted in the Service, or on delivery by post or courier.` },
        { p: "You agree that all agreements, notices, disclosures and other communications we provide electronically satisfy any legal requirement that they be in writing." },
      ],
    },
    {
      id: "changes",
      title: "34. Changes to these Terms",
      blocks: [
        { p: "We may update these Terms from time to time. If we make a material change, we will notify the Account Owner by email and by notice in the Service at least 30 days before the change takes effect, unless the change is required sooner by law or relates to a new feature, in which case it takes effect when posted. The updated Terms will show a new version number and effective date. If you do not agree to a material change, you may cancel your subscription before it takes effect and, if you have prepaid for an annual plan, request a refund of prepaid fees for the unused remainder of the then-current billing period. Your continued use of the Service after a change takes effect constitutes acceptance of the updated Terms." },
      ],
    },
    {
      id: "general",
      title: "35. General",
      blocks: [
        { list: [
          "**Entire agreement.** The Agreement is the entire agreement between the parties regarding its subject matter and supersedes all prior or contemporaneous agreements, proposals and representations. Terms in any purchase order or other document you provide do not apply.",
          "**Assignment.** You may not assign or transfer the Agreement without our prior written consent. We may assign the Agreement without consent in connection with a merger, acquisition, corporate reorganization or sale of all or substantially all of our assets or of the business to which the Agreement relates, with notice to you. Any attempted assignment in violation of this paragraph is void.",
          "**Force majeure.** Neither party is liable for any delay or failure to perform (other than payment obligations) caused by events beyond its reasonable control, including natural disasters, epidemics, war, terrorism, labor disputes, governmental action, utility or internet failures, or failures of third-party hosting or communications providers.",
          "**Relationship.** The parties are independent contractors. The Agreement does not create a partnership, joint venture, agency or employment relationship.",
          "**No third-party beneficiaries.** There are no third-party beneficiaries of the Agreement, including your clients and Invited Users.",
          "**Severability; waiver.** If any provision is held unenforceable, it will be enforced to the maximum extent permissible and the rest of the Agreement will remain in effect. A failure or delay in enforcing a provision is not a waiver of it.",
          "**Interpretation.** Headings are for convenience only. “Including” means “including without limitation.”",
        ] },
      ],
    },
    {
      id: "contact",
      title: "36. Contact",
      blocks: [
        { p: `${name} · ${addressOneLine} · United States · [${email}](mailto:${email})` },
      ],
    },
  ],
};
