export const planCards = [
  {
    key: "solo",
    name: "Solo",
    monthlyCents: 6_900,
    yearlyCents: 69_000,
    monthly: "$69",
    yearly: "$690",
    description: "A calm operating system for an established solo photographer.",
    users: "1 internal user",
    ai: "500 AI actions",
    highlight: false,
    features: [
      "Unlimited clients and projects",
      "Core readiness and workflow automation",
      "Client portal and standard integrations",
      "Up to 10 active subcontractors",
    ],
  },
  {
    key: "studio",
    name: "Studio",
    monthlyCents: 19_900,
    yearlyCents: 199_000,
    monthly: "$199",
    yearly: "$1,990",
    description: "Complete event operations for growing photography teams.",
    users: "5 internal users",
    ai: "2,500 AI actions",
    highlight: true,
    features: [
      "Unlimited clients, projects, and subcontractors",
      "COI workflows and custom automations",
      "AI schedule generation and crew acknowledgement",
      "Advanced readiness reporting and priority support",
    ],
  },
  {
    key: "multi_brand",
    name: "Multi-Brand",
    monthlyCents: 39_900,
    yearlyCents: 399_000,
    monthly: "$399",
    yearly: "$3,990",
    description: "Standardized operations across larger teams and brands.",
    users: "15 internal users",
    ai: "7,500 AI actions",
    highlight: false,
    features: [
      "Everything in Studio",
      "3 separately branded businesses",
      "Advanced permissions and portfolio reporting",
      "API access and priority onboarding",
    ],
  },
] as const;

