"use client";
import { useEffect,useState } from "react";
import { getFirebaseClient } from "@/lib/firebase/client";
import { getAppCheckToken } from "@/lib/firebase/app-check";
type AdminCommand=
  |{type:"setFeatureFlag";input:{key:string;enabled:boolean;tenantIds:string[];description:string}}
  |{type:"suspendTenant";input:{tenantId:string;reason:string}}
  |{type:"grantSupportAccess";input:{tenantId:string;reason:string;durationMinutes:number}}
  |{type:"rerunJob";input:{jobId:string}}
  |{type:"revokeSupportAccess";input:{supportAccessId:string;reason:string}}
  |{type:"approveDeletion";input:{requestId:string;reason:string}};
export function AdminCommandAction({label,complete,command}:{label:string;complete:string;command:AdminCommand}){const[ready,setReady]=useState(false);const[notice,setNotice]=useState<string|null>(null);useEffect(()=>{const frame=requestAnimationFrame(()=>setReady(true));return()=>cancelAnimationFrame(frame)},[]);const run=async()=>{const endpoint=process.env.NEXT_PUBLIC_SAAS_ADMIN_FUNCTIONS_URL;if(!endpoint){setNotice(`Development preview: ${complete} No platform record changed.`);return}try{const{auth}=getFirebaseClient();const user=auth.currentUser;if(!user)throw new Error("Sign in as a platform administrator.");const appCheckToken=await getAppCheckToken();const response=await fetch(`${endpoint.replace(/\/$/,"")}/saasAdminCommand`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${await user.getIdToken()}`,...(appCheckToken?{"x-firebase-appcheck":appCheckToken}:{})},body:JSON.stringify(command)});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error??"Platform operation failed.");setNotice(complete)}catch(caught:unknown){setNotice(caught instanceof Error?caught.message:"Platform operation failed.")}};return <div><button className="button button-dark" disabled={!ready} type="button" onClick={()=>void run()}>{label}</button>{notice?<p className="form-notice" role="status">{notice}</p>:null}</div>}

export function SupportAccessForm(){const[tenantId,setTenantId]=useState("");const[reason,setReason]=useState("");const[notice,setNotice]=useState<string|null>(null);const[summary,setSummary]=useState<Record<string,unknown>|null>(null);const run=async()=>{if(!tenantId.trim()||reason.trim().length<10){setNotice("Enter a tenant ID and a reason of at least 10 characters.");return}const endpoint=process.env.NEXT_PUBLIC_SAAS_ADMIN_FUNCTIONS_URL;if(!endpoint){setNotice("Development preview: temporary access was validated but no support grant was created.");return}try{const{auth}=getFirebaseClient();const user=auth.currentUser;if(!user)throw new Error("Sign in as a platform administrator.");const appCheckToken=await getAppCheckToken();const headers={"content-type":"application/json",authorization:`Bearer ${await user.getIdToken()}`,...(appCheckToken?{"x-firebase-appcheck":appCheckToken}:{})};const response=await fetch(`${endpoint.replace(/\/$/,"")}/saasAdminCommand`,{method:"POST",headers,body:JSON.stringify({type:"grantSupportAccess",input:{tenantId:tenantId.trim(),reason:reason.trim(),durationMinutes:30}})});const result=await response.json() as {error?:string;supportAccessId?:string};if(!response.ok||!result.supportAccessId)throw new Error(result.error??"Support grant failed.");const summaryResponse=await fetch(`${endpoint.replace(/\/$/,"")}/supportTenantSummary?tenantId=${encodeURIComponent(tenantId.trim())}&accessId=${encodeURIComponent(result.supportAccessId)}`,{headers:{authorization:headers.authorization,...(appCheckToken?{"x-firebase-appcheck":appCheckToken}:{})}});const summaryResult=await summaryResponse.json() as Record<string,unknown>;if(!summaryResponse.ok)throw new Error(typeof summaryResult.error==="string"?summaryResult.error:"Support summary failed.");setSummary(summaryResult);setNotice("Temporary support access granted for 30 minutes. This summary view was audited.")}catch(caught:unknown){setNotice(caught instanceof Error?caught.message:"Support grant failed.")}};return <form className="support-access-form" onSubmit={event=>{event.preventDefault();void run()}}><label>Tenant ID<input value={tenantId} onChange={event=>setTenantId(event.target.value)} placeholder="Enter the exact tenant ID"/></label><label>Business reason<textarea value={reason} onChange={event=>setReason(event.target.value)} placeholder="Describe the customer-reported issue"/></label><button className="button button-dark" type="submit">Grant 30-minute access</button>{notice?<p className="form-notice" role="status">{notice}</p>:null}{summary?<pre className="support-summary">{JSON.stringify(summary,null,2)}</pre>:null}</form>}
