import { defineHowTo } from "../lib/define";

/** The journey film, chapter 6: planning (docs/wedding-journey-video-plan-2026-10-02.md §3). */
export default defineHowTo({
  id: "journey-6",
  title: "One wedding, start to finish: planning",
  start: { as: "owner", viewport: "desktop" },
  cast: { studio: "owner", couple: "ella.hart@studiohub.test", crew: "crew" },
  steps: [
    { do: [{ story: "wedding-in:178" }, { story: "scheduler:planning/planning-form-scheduler.ts#planningFormScheduler" }] },
    {
      chapter: "Planning",
      on: "studio",
      layout: "studio",
      when: { at: 0.4, label: "6 months to go" },
      say: "Six months out, planning begins. Your next move on the job is the planning form. One tap sends it.",
      do: [
        { goto: "/studio/projects/{job}" },
        { waitFor: { css: ".thread-next-go" } },
        { wait: 600 },
        { spotlight: { css: ".thread-next" }, holdMs: 2200 },
        { click: { css: ".thread-next-go" } },
        { waitFor: { role: "button", name: "Send the form" } },
        { wait: 500 },
        { click: { role: "button", name: "Send the form" } },
        { wait: 2000 },
      ],
    },
    { do: [{ story: "drain:undo" }] },
    {
      on: "couple",
      layout: "phone",
      caption: { title: "What Ella sees", detail: "Her planning form, already started." },
      say: "Ella's form arrives already filled in with what you know: their names, the venue, the ceremony time. She adds the rest, over a few evenings.",
      do: [
        { goto: "/client/questionnaire" },
        { waitFor: { css: "h1.kit-title" } },
        { wait: 800 },
        { spotlight: { text: "Filled in from your booking. You can change it.", nth: 0 }, holdMs: 2400 },
        { type: { into: { css: "main input:not([value]), main input[value='']" }, text: "Sophie Hart, 617 555 0144" } },
        { wait: 600 },
      ],
    },
    { do: [{ story: "questionnaire-done" }] },
    {
      on: "studio",
      layout: "studio",
      when: { at: 0.45, label: "5 months to go" },
      say: "When her answers are in, StudioCue drafts the run of show from them, and shows where every time came from.",
      do: [
        { goto: "/studio/projects/{job}" },
        { waitFor: { css: ".thread-next-go" } },
        { click: { css: ".thread-next-go" } },
        { waitFor: { role: "button", name: "Generate draft" } },
        { respond: { url: "**/aiScheduleCommand", with: "schedule-draft" } },
        { scrollTo: { role: "button", name: "Generate draft" } },
        { click: { role: "button", name: "Generate draft" } },
        { wait: 2500 },
        { scrollBy: 650 },
        { wait: 1500 },
      ],
      poster: true,
    },
    {
      on: "studio",
      say: "Change anything you like, then publish it.",
      do: [
        { scrollTo: { role: "button", name: "Publish reviewed schedule" } },
        { spotlight: { role: "button", name: "Publish reviewed schedule" }, holdMs: 1400 },
        { click: { role: "button", name: "Publish reviewed schedule" } },
        { wait: 2500 },
      ],
    },
    { do: [{ story: "drain" }] },
    {
      on: "couple",
      layout: "phone",
      caption: { title: "What Ella sees", detail: "The day, hour by hour." },
      say: "Ella checks the timeline on her phone, and approves it,",
      do: [
        { goto: "/client/schedule" },
        { waitFor: { role: "button", name: "Approve timeline" } },
        { wait: 1200 },
        { scrollBy: 500 },
        { wait: 900 },
        { click: { role: "button", name: "Approve timeline" } },
        { wait: 2200 },
      ],
    },
    { do: [{ story: "drain" }] },
    {
      on: "crew",
      layout: "phone",
      caption: { title: "What Jordan sees", detail: "Their day sheet." },
      say: "and Jordan gets the day sheet: where to be, and when.",
      do: [
        { goto: "/crew/jobs" },
        { waitFor: { css: "h1.kit-title" } },
        { click: { text: "Ella Hart Wedding" } },
        { waitFor: { text: "Day sheet", exact: true } },
        { wait: 900 },
        { click: { text: "Day sheet", exact: true } },
        { wait: 2500 },
        { scrollBy: 450 },
        { wait: 800 },
      ],
    },
    { do: [{ story: "wedding-in:27" }, { story: "scheduler:planning/final-details.ts#finalDetailsScheduler" }, { story: "scheduler:operations/invoice-scheduler.ts#finalInvoiceScheduler" }, { story: "scheduler:communications/lifecycle-scheduler.ts#lifecycleMessageScheduler" }] },
    {
      on: "couple",
      layout: "phone",
      when: { at: 0.55, label: "4 weeks to go" },
      caption: { title: "What Ella sees", detail: "Four weeks out: everything, one last time." },
      say: "Four weeks out, the details lock. Ella sees everything for the day in one place, and confirms it. After that, a change to where or when comes to you to agree.",
      do: [
        { goto: "/client" },
        { waitFor: { role: "button", name: "Confirm our final details" } },
        { wait: 1200 },
        { scrollBy: 500 },
        { wait: 900 },
        { scrollTo: { role: "button", name: "Confirm our final details" } },
        { click: { role: "button", name: "Confirm our final details" } },
        { wait: 2200 },
      ],
    },
    { do: [{ story: "retainer-link:final" }] },
    {
      on: "couple",
      say: "The final balance invoice has already gone out by itself. She can pay it now, or let a saved card pay it on the due date.",
      do: [
        { goto: "/client/payments" },
        { waitFor: { css: "h1.kit-title" } },
        { wait: 1200 },
        { spotlight: { text: /^Pay .* securely/ }, holdMs: 2400 },
      ],
    },
  ],
});
