import { defineHowTo } from "../lib/define";

/** The journey film, chapter 8: after the wedding (docs/wedding-journey-video-plan-2026-10-02.md §3). */
export default defineHowTo({
  id: "journey-8",
  title: "One wedding, start to finish: after the wedding",
  start: { as: "owner", viewport: "desktop" },
  cast: { studio: "owner", couple: "ella.hart@studiohub.test", crew: "crew" },
  steps: [
    { do: [{ story: "wedding-in:-1" }] },
    {
      chapter: "After the wedding",
      on: "studio",
      layout: "studio",
      when: { at: 0.64, label: "The day after" },
      say: "The day after, the job asks one question: did it go ahead? One tap, and it moves on.",
      do: [
        { goto: "/studio/projects/{job}" },
        { waitFor: { css: ".thread-next" } },
        { wait: 800 },
        { spotlight: { css: ".thread-next" }, holdMs: 2200 },
        { click: { css: ".thread-next button:has-text('Yes, we shot it')" } },
        { wait: 2200 },
      ],
    },
    {
      on: "crew",
      layout: "phone",
      caption: { title: "What Jordan sees", detail: "Hours and expenses, from their phone." },
      say: "Jordan sends their hours and any expenses from their phone, for you to approve and pay.",
      do: [
        { goto: "/crew/closeout" },
        { waitFor: { role: "button", name: "Send to the studio" } },
        { wait: 1400 },
        { click: { role: "button", name: "Send to the studio" } },
        { wait: 2000 },
      ],
    },
    { do: [{ story: "drain" }, { story: "editing-started" }, { story: "wedding-in:-30" }, { story: "gallery-ready" }] },
    {
      on: "studio",
      layout: "studio",
      when: { at: 0.78, label: "6 weeks after" },
      say: "When the edit is done, open the Delivery tab, paste the link to the gallery,",
      do: [
        { goto: "/studio/delivery?project={job}" },
        { waitFor: { role: "heading", name: "Send photos or a film" } },
        { wait: 600 },
        { scrollTo: { css: "input[placeholder^='https']" } },
        { type: { into: { css: "input[placeholder^='https']" }, text: "https://alderandmuse.pic-time.com/ella-marcus" } },
        { wait: 400 },
        { cut: [
          { scrollTo: { text: "This completes delivery: review asks and album" } },
          { click: { text: "This completes delivery: review asks and album" } },
          { fill: { into: { css: "label:has-text('Review link') input" }, value: "https://g.page/r/alder-and-muse/review" } },
        ] },
      ],
      poster: true,
    },
    {
      on: "studio",
      say: "and release it.",
      do: [
        { scrollTo: { role: "button", name: /Release/ } },
        { click: { role: "button", name: /Release/ } },
        { waitFor: { role: "button", name: "Yes, release and complete delivery" } },
        { wait: 500 },
        { click: { role: "button", name: "Yes, release and complete delivery" } },
        { wait: 2200 },
      ],
    },
    { do: [{ story: "drain:undo" }] },
    {
      on: "couple",
      layout: "split",
      caption: { title: "Ella" },
      say: "Ella gets one email, and her gallery is waiting in her portal.",
      do: [{ email: { subject: /photographs are ready/i, to: "ella.hart@studiohub.test" } }, { wait: 2600 }],
    },
    {
      on: "couple",
      layout: "phone",
      caption: { title: "What Ella sees", detail: "Her photos, and a gentle ask." },
      say: "She downloads everything,",
      do: [
        { goto: "/client/delivery" },
        { waitFor: { role: "button", name: "I’ve downloaded everything" } },
        { wait: 1500 },
        { click: { role: "button", name: "I’ve downloaded everything" } },
        { wait: 1500 },
      ],
    },
    { do: [{ story: "review-due:1" }] },
    {
      on: "couple",
      when: { at: 0.82, label: "7 weeks after" },
      say: "and a few days later, she's asked for a review, then once more by email if she hasn't left one.",
      do: [
        { goto: "/client/reviews" },
        { waitFor: { css: "h1.kit-title" } },
        { wait: 1500 },
        { spotlight: { text: /Leave a review/ }, holdMs: 1800 },
        { click: { role: "button", name: "I’ve left my review" } },
        { wait: 1500 },
      ],
    },
    {
      on: "studio",
      layout: "studio",
      when: { at: 0.95, label: "10 weeks after" },
      say: "Last, Wrap up checks everything is settled: the agreement, the balance, the gallery, the review and the crew. Anything StudioCue can't see, you vouch for.",
      do: [
        { goto: "/studio/delivery?project={job}" },
        { waitFor: { text: "Wrap up" } },
        { scrollTo: { text: "Wrap up" } },
        { wait: 800 },
        { click: { text: "Mark as done" } },
        { waitFor: { role: "button", name: "Record it" } },
        { type: { into: { css: "input[placeholder*='confirmed']" }, text: "Jordan's hours approved and paid" } },
        { wait: 500 },
        { click: { role: "button", name: "Record it" } },
        { cut: [{ waitFor: { text: /8 of 8|Everything reconciles|1 of 8 on your word/ }, timeoutMs: 20000 }, { wait: 600 }] },
        { clickIfShown: { role: "button", name: "Check again" }, withinMs: 1500 },
        { waitFor: { role: "button", name: "Close and archive" }, timeoutMs: 20000 },
        { scrollTo: { role: "button", name: "Close and archive" } },
        { wait: 600 },
      ],
    },
    {
      on: "studio",
      when: { at: 1, label: "Closed" },
      say: "Close it, and the wedding is done: from the first email to the last photo, in one place.",
      do: [{ click: { role: "button", name: "Close and archive" } }, { wait: 2500 }],
      pauseAfterMs: 1200,
    },
    {
      do: [
        { card: { eyebrow: "One wedding, start to finish", title: "{tally.auto} emails to Ella and Jordan.", subtitle: "StudioCue wrote every one. You approved the ones that mattered." } },
        { wait: 3600 },
      ],
    },
    { do: [{ card: { eyebrow: "StudioCue", title: "Your next wedding, start to finish.", subtitle: "Start your free trial at studio-cue.com" } }, { wait: 3200 }] },
  ],
});
