import { defineHowTo } from "../lib/define";

/** The journey film, chapter 3: proposal, agreement, retainer — booked (docs/wedding-journey-video-plan-2026-10-02.md §3). */
export default defineHowTo({
  id: "journey-3",
  title: "One wedding, start to finish: booking",
  start: { as: "owner", viewport: "desktop" },
  cast: { studio: "owner", couple: "ella.hart@studiohub.test" },
  before: ["ella-joins"],
  steps: [
    {
      chapter: "Booking",
      on: "studio",
      layout: "studio",
      when: { at: 0.1, label: "13 months to go" },
      say: "After the call, open their job. The green card says what's next: the proposal.",
      do: [{ goto: "/studio/projects/{job}" }, { waitFor: { css: ".thread-next-go" } }, { wait: 800 }, { spotlight: { css: ".thread-next" }, holdMs: 2600 }],
    },
    {
      on: "studio",
      say: "Pick the package they want.",
      do: [
        { click: { css: ".thread-next-go" } },
        { waitFor: { role: "heading", name: "Choose the client and event" } },
        { wait: 800 },
        { scrollTo: { role: "button", name: "Lock this package", nth: 2 } },
        { hover: { role: "button", name: "Lock this package", nth: 2 } },
        { wait: 400 },
        { click: { role: "button", name: "Lock this package", nth: 2 } },
        { wait: 1200 },
        { spotlight: { css: ".proposal-composer-preview" }, holdMs: 2400 },
      ],
    },
    {
      on: "studio",
      say: "The price, the retainer and the dates fill in from your settings. Approve it, and send.",
      do: [
        { scrollTo: { role: "button", name: "Create draft" } },
        { click: { role: "button", name: "Create draft" } },
        { cut: [{ waitFor: { role: "button", name: "Approve this proposal" }, timeoutMs: 90000 }, { wait: 500 }] },
        { click: { role: "button", name: "Approve this proposal" } },
        { cut: [{ waitFor: { text: "Branded PDF ready" }, timeoutMs: 120000 }, { wait: 500 }] },
        { click: { css: "label:has-text('Ready to share with the client') input" } },
        { wait: 400 },
        { click: { role: "button", name: "Send proposal" } },
        { wait: 1500 },
      ],
      pauseAfterMs: 800,
    },
    { do: [{ story: "drain" }] },
    {
      on: "couple",
      layout: "phone",
      caption: { title: "What Ella sees", detail: "Her proposal, in your brand." },
      say: "Ella gets your proposal by email, and opens it in her own wedding portal.",
      do: [{ email: { subject: /proposal/i, to: "ella.hart@studiohub.test" } }, { wait: 1800 }],
    },
    {
      on: "couple",
      say: "She sees exactly what's included, the payment plan, and any extras she could add. When she's happy, she accepts.",
      do: [
        { goto: "/client/proposal" },
        { waitFor: { css: "h1.kit-title" } },
        { wait: 1200 },
        { scrollBy: 420 },
        { wait: 1400 },
        { scrollBy: -420 },
        { click: { role: "button", name: "Accept proposal" } },
        { wait: 900 },
        { click: { role: "button", name: "Confirm acceptance" } },
        { wait: 2500 },
      ],
    },
    { do: [{ story: "drain" }] },
    {
      on: "couple",
      layout: "split",
      caption: { title: "Ella" },
      say: "The moment she accepts, the agreement goes out: written from that proposal, and already signed for you.",
      do: [{ email: { subject: /agreement|sign/i, to: "ella.hart@studiohub.test" } }, { wait: 1500 }],
    },
    {
      on: "couple",
      layout: "phone",
      caption: { title: "What Ella sees", detail: "The agreement, signed on her phone." },
      say: "She reads it, and signs on her phone.",
      do: [
        { goto: "/client/contract" },
        { waitFor: { role: "button", name: /Review & sign/ } },
        { wait: 1500 },
        { click: { role: "button", name: /Review & sign/ } },
        { waitFor: { role: "dialog", name: /.+/ } },
        { click: { css: ".sheet-dialog input[type='checkbox']" } },
        { type: { into: { css: ".sheet-dialog input[type='text'], .sheet-dialog input:not([type])" }, text: "Ella Hart" } },
        { click: { css: ".sheet-dialog button:has-text('Sign')" } },
        { wait: 3000 },
      ],
    },
    { do: [{ story: "drain" }] },
    { do: [{ story: "retainer-link" }] },
    {
      on: "couple",
      layout: "phone",
      caption: { title: "What Ella sees", detail: "The retainer that holds her date." },
      say: "Next comes the retainer, which holds her date. She pays it online, in a minute.",
      do: [
        { goto: "/client/payments" },
        { waitFor: { css: "h1.kit-title" } },
        { wait: 1500 },
        { spotlight: { text: /^Pay .* securely/ }, holdMs: 2400 },
      ],
    },
    { do: [{ story: "retainer-paid" }] },
    {
      on: "studio",
      layout: "studio",
      when: { at: 0.2, label: "12 months to go" },
      say: "Back on your side, the agreement is signed and the retainer is paid, so the booking is confirmed: her portal, the planning checklist and the calendar are set up for you.",
      do: [
        { goto: "/studio/booking?project={job}" },
        { waitFor: { css: ".booking-progress" } },
        { scrollTo: { css: ".booking-progress" } },
        { spotlight: { css: ".booking-progress" }, holdMs: 2800 },
        { clickIfShown: { role: "button", name: "Check and confirm" } },
        { waitFor: { text: /Booking is confirmed|Booked on/ }, timeoutMs: 30000 },
        { scrollTo: { text: /Booking is confirmed|Booked on/ } },
        { spotlight: { text: /Booking is confirmed|Booked on/ }, holdMs: 3000 },
      ],
      poster: true,
    },
    {
      on: "studio",
      say: "Booked, without a single chase.",
      do: [{ wait: 1200 }],
    },
  ],
});
