import { getFirestore } from "firebase-admin/firestore";
import { getStorage } from "firebase-admin/storage";
import { onObjectFinalized } from "firebase-functions/v2/storage";
import { consumeAiQuota } from "../saas/usage.js";

async function identityToken(audience:string){const response=await fetch(`http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=${encodeURIComponent(audience)}&format=full`,{headers:{"Metadata-Flavor":"Google"}});if(!response.ok)throw new Error("FILE_SCANNER_IDENTITY_UNAVAILABLE");return response.text()}
export const fileSafetyOnFinalize=onObjectFinalized({region:"us-east1",cpu:1,memory:"512MiB",timeoutSeconds:120},async event=>{const object=event.data;const name=object.name;if(!name||!name.startsWith("tenants/"))return;const contentType=object.contentType??"application/octet-stream";const file=getStorage().bucket(object.bucket).file(name);const id=Buffer.from(`${object.bucket}/${name}/${object.generation}`).toString("base64url").slice(0,900);const reference=getFirestore().doc(`fileScans/${id}`);const now=new Date().toISOString();const service=process.env.MALWARE_SCAN_SERVICE_URL;
  if(object.metadata?.trustedGenerator||object.metadata?.scanStatus==="clean")return;
  if(!service){await file.setMetadata({metadata:{...(object.metadata??{}),scanStatus:"scanner_unavailable"}});await reference.set({id,bucket:object.bucket,objectName:name,generation:object.generation,contentType,status:"scanner_unavailable",createdAt:now,updatedAt:now});return}
  try{const audience=service.replace(/\/$/,"");const token=await identityToken(audience);const response=await fetch(`${audience}/v1/scan`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({bucket:object.bucket,object_name:name,expected_content_type:contentType,max_bytes:25*1024*1024})});const result=await response.json() as{status?:string;engine?:string;detail?:string};const status=response.ok&&result.status==="clean"?"clean":result.status==="infected"?"infected":"rejected";await file.setMetadata({metadata:{...(object.metadata??{}),scanStatus:status,scanEngine:result.engine??"file-safety"}});await reference.set({id,bucket:object.bucket,objectName:name,generation:object.generation,contentType,status,detail:result.detail??null,createdAt:now,updatedAt:now});
    const coiRequestId=object.metadata?.coiRequestId;
    if(coiRequestId){const db=getFirestore();const coi=db.doc(`insuranceRequests/${coiRequestId}`);if(status!=="clean"){await coi.update({scanStatus:status,status:"failed",updatedAt:now,updatedBy:"file-safety"});return}try{await db.runTransaction(async transaction=>{const current=await transaction.get(coi);if(!current.exists)throw new Error("INSURANCE_REQUEST_NOT_FOUND");const aiJob=db.doc(`aiJobs/coi_${coiRequestId}`);if((await transaction.get(aiJob)).exists)return;await consumeAiQuota(transaction,db,String(current.get("tenantId")),now);transaction.update(coi,{scanStatus:"clean",status:"received",updatedAt:now,updatedBy:"file-safety"});transaction.create(aiJob,{tenantId:current.get("tenantId"),projectId:current.get("projectId"),type:"coi_extraction",status:"queued",attempts:0,humanApprovalRequired:true,createdAt:now,updatedAt:now})})}catch(caught:unknown){await coi.update({scanStatus:"clean",aiQueueError:caught instanceof Error?caught.message:"AI_QUEUE_FAILED",updatedAt:now,updatedBy:"file-safety"})}}
  }catch(caught:unknown){await file.setMetadata({metadata:{...(object.metadata??{}),scanStatus:"scan_failed"}});await reference.set({id,bucket:object.bucket,objectName:name,generation:object.generation,contentType,status:"scan_failed",detail:caught instanceof Error?caught.message:"SCAN_FAILED",createdAt:now,updatedAt:now});const coiRequestId=object.metadata?.coiRequestId;if(coiRequestId)await getFirestore().doc(`insuranceRequests/${coiRequestId}`).update({scanStatus:"scan_failed",status:"failed",updatedAt:now,updatedBy:"file-safety"})}});
